### PR TITLE
Create unit_respawning.lua

### PR DESCRIPTION
**Pull request by Xehrath**
This gadget enables unit respawning at a designated target. This is mainly intended for Evocom.

### CODE REVIEW

**Comment by SethDGamre** [comment]
Testing notes

Burstfire weapons will continue to track the transposed(respawning) unit even after transposition across the map. An example of this is the Cortex Pyro. Its burst of flame follows the commander across the map and because it only has 1 HP remaining when transposition occurs, the commander dies immediately. I suggest an "immunity" timer where the commander is immune to all damage. 5 seconds should be sufficient.

When the effigy first spawns in it is offset from commander's starting position. Which means sometimes it can end up in a place from which the commander cannot move. Instead, I think it should spawn in the exact same spot as the commander because the commander can just move away from it. And, if it was a "respawn pad", the commander would have to respawn in that exact spot anyways. in either case, the commander will be able to move, and the initial effigy respawn location will be traversable.

**Comment by SethDGamre** [comment]
need to add "iseffigy" customparam instructions in the comment section at the top of the gadget

**Comment by SethDGamre** [comment]
When a unit with an effigy dies, its effigy should die too. Otherwise, since they're invisible and completely undetectable (not talking about the respawn pad method here), games with "kill all units" win condition will be unwinnable because the undetectable effigy still counts as a unit.

This happens when the commander self destructs, currently the effigy doesn't die or transpose with commander.

**Comment by SethDGamre** [comment]
when a new effigy is built, the old one disappears. This is fine for commanders, but if you want this gadget to be usable for more than just a single unit with multiple effigies, this isn't ideal.

**Comment by SethDGamre** [comment]
https://youtu.be/jf6tmAFROkc

Looking good! we need two more things:

1. A cosmetic indicator of how much time the commander will be paralyzed for after respawn.

2. Need to clear out all of the respawned unit's commands so it doesn't immediately walk back into battle with 0 HP unexpectedly.

**Comment by Xehrath** [comment]
This should be ready for a merge now, unless someone finds anything else.

**Pull request merged**
