### PR TITLE
Add autogroups on UnitCreated

### LINKED ISSUE #3449: Add additional option for "Autogroup immediate mode" that adds a unit into autogroup while it's being built
### Description

Currently, if a unit is being built, it's not added to autogroup with "Autogroup immediate mode": ON, until it leaves the factory.

image

### Why?

This makes for clunky micro when you want to rally a single unit to defend your base. I usually use _group unset_, instinctively, but that doesn't work, as the autogroup currently assigns it when it leaves the factory. Group unset does nothing.

### What area of the game does this feature request pertain?

Gameplay, UI/UX, Settings, Controls or Hotkeys

### Other (optional)

_No response_

### PR DESCRIPTION
**Pull request by hihoman23**
### Work done
The autogroup widget adds the control groups on unit creation on immediate mode.

closes #3449

### CODE REVIEW

**Comment by badosu** [comment]
This is a very problematic piece of code, I am unable to review or test this properly, I just want to remark to thoroughly test the autogroup widget use cases (immediate mode on/off, built from factory with order/not, rezzed, given, captured, etc)

**Comment by WatchTheFort** [comment]
@hihoman23 Has this been tested in line with badosu's comment?

**Comment by hihoman23** [comment]
No, I sadly haven’t gotten to it.

**Comment by badosu** [comment]
Yeah, don't mean to block others work unnecessarily. 

It's just too often we see contributions in widgets with lots of features creating regressions up to a point they get unusable later and very hard to fix back to original state (e.g. mex snap, that I had to fix like 4 times over again until I simply gave up).

**Comment by sprunk** [comment]
Could have testing instructions in the comments, listing cases.

**Review by robertthepie — APPROVED** [review]

**Pull request merged**
