### PR TITLE
Updated Claws and Maws range to account for 'bonus' overshooting

### PR DESCRIPTION
**Pull request by TheSilverHornet**
Claws and maws overshoot their range too readily, which is a issue with countering their longer ranged 'counters'.

- Maws had no benefit from 'weapontimer', the tag is meaningless and thus removed
 - burnblow in theory is the answer, but in reality appears not to work as advertised, this is pending engine investigation
 
 - Claws have excessive range especially when force fired, a combination of factors can allow them to hit units shooting them, despite having an on paper 65 range disadvantage.  With maw overshoot fixed this makes them even more powerful in comparison, so range reduced a touch, and groundfire disabled

The PR is currently paused pending evaluation of impact from the hitbox changes, and ideally also engine level evaluation of why burnblow does not in fact remove the fire projectiles at max range, potentially relating to them bouncing?

### CODE REVIEW

**Comment by Beherith** [comment]
'Zealous' is not a straightforward description. Please preface unitdef changes with reasoning. `.` is not an acceptable commit message for an actual balance change. 
Is the -10 range wanted because of AoE calculation or lightning splash?
Is the preventing of ground firing wanted because of lightning splash?

An actual (probably incorrect) PR description of the above commits should rather look like:


- armclaw
  - Set canattackground = false, to prevent lighting splash overreaches
  - Reduced range from 430 to 420 because ...
  
- cormaw
  - Set burnblow = true, to ensure projectile removal at max range. 
  - Removed spurious weapontimer = 1, that only affects starburst missiles

**Comment by TheSilverHornet** [comment]
This was related to a conversation elsewhere, it made sense within context, but agreed it makes sense to be more verbose for benefit of those outside it.  In short both claws and maws can overshoot their real range, in different ways, this addresses that.  

With the maw overshoot fixed, the claw is too long ranged in comparision, especially considering it has better mechanics than the maw to begin with, hence the -10.  The removal of ground fire is indeed to prevent extra range hackery; emit point distance + range + splash overshoot can allow them to hit units they should be handily outranged by.

The PR is currently paused pending evaluation of impact from the hitbox changes, and ideally also engine level evaluation of why burnblow does not in fact remove the fire projectiles at max range, potentially relating to them bouncing?



Internal commit names are generally irrelevant as PRs are usually squashmerged, they're just a minor update to the previous, the title of the PR becomes the main branch commit message, and the PR should be considered as a whole rather than any individual commit within it. This was discussed at length on discord somewhere and the conclusion boiled down to 'squash merge makes it irrelevant'. However I realise others seem to have different views, and as it might potentially make reviews confusing in some cases, I will try to make them more detailed where applicable. Some things really are just 'typo', 'didn't save previous file', 'wrong version', nothing remotely relevant or that should end up as a commit message in main repo anyway.

**Comment by Beherith** [comment]
> This was related to a conversation elsewhere, it made sense within context, but agreed it makes sense to be more verbose for benefit of those outside it. In short both claws and maws can overshoot their real range, in different ways, this addresses that.
> 
> With the maw overshoot fixed, the claw is too long ranged in comparision, especially considering it has better mechanics than the maw to begin with, hence the -10. The removal of ground fire is indeed to prevent extra range hackery; emit point distance + range + splash overshoot can allow them to hit units they should be handily outranged by.

Was the range reduction derived empirically or via calculation? 

> The PR is currently paused pending evaluation of impact from the hitbox changes, and ideally also engine level evaluation of why burnblow does not in fact remove the fire projectiles at max range, potentially relating to them bouncing?

Are you just making a guess or did you look at engine source?

```c++
WEAPONTAG(bool, selfExplode).externalName("burnblow").defaultValue(false).description("For LaserCannon, expire when reaching the target (at max range otherwise). For Cannon, explode when reaching the target (keep falling otherwise). For Missile/Starburst/TorpedoLauncher, explode when running out of fuel (fall down otherwise).");
```
Seeing as FlameThrower is inherits from the base Weapon Class, and only overrides its FireImpl method
```
#ifndef _FLAME_THROWER_H
#define _FLAME_THROWER_H

#include "Weapon.h"

class CFlameThrower: public CWeapon
{
	CR_DECLARE_DERIVED(CFlameThrower)
public:
	CFlameThrower(CUnit* owner = nullptr, const WeaponDef* def = nullptr): CWeapon(owner, def) {}

	float3 color;
	float3 color2;

private:
	void FireImpl(const bool scriptCall) override final;
};

#endif // _FLAME_THROWER_H

```

A quick search for `selfExplode` seems to indicate is has no effect on flame weapons or flame projectiles:

image


Did enabling burnblow for the weapon seem to have any effect, especially if it contradicts the information above?

> Internal commit names are generally irrelevant as PRs are usually squashmerged, they're just a minor update to the previous, the title of the PR becomes the main branch commit message, and the PR should be considered as a whole rather than any individual commit within it. This was discussed at length on discord somewhere and the conclusion boiled down to 'squash merge makes it irrelevant'.

As I said, **for an actual balance change**

> However I realise others seem to have different views, and as it might potentially make reviews confusing in some cases, I will try to make them more detailed where applicable. Some things really are just 'typo', 'didn't save previous file', 'wrong version', nothing remotely relevant or that should end up as a commit message in main repo anyway.

Indeed, some things are indeed typo et al, but that is not the case here.

**Comment by sprunk** [comment]
That would result in visually confusing sparks that seem to "avoid" enemy units. Also all other forms of splash can reach beyond their nominal range by hitting at the edge, what makes lightning different enough to warrant it?
image

**Comment by TheSilverHornet** [comment]
> Was the range reduction derived empirically or via calculation?
Both; claws have +20 weapondefinition range advantage compared to maws, then gain more from both the extra splash and a little from emission point off centre (the latter quirk shared with the maw). Losing some of the literal base range should help make them fairer.

> Are you just making a guess or did you look at engine source?
> Did enabling burnblow for the weapon seem to have any effect, especially if it contradicts the information above?
As to whether burnblow should work, or that it does not? I initially assumed it would work, observed it did not seem to, then investigated and discussed that problem elsewhere.  As for bounce specificially being a possibility, Sprung suggested that, and he knows the engine code much better than I do.  Your writeup does seem to indicate that it would never work, bouncing aside, which matches behavior seen by myself and others.  Engine ticket for this already exists, might be better to dive deeper there; https://github.com/beyond-all-reason/spring/issues/1630

Regarding subcommit names, I agree as it currently stands - but when the PR is squashmerged in, those commit names are removed, leaving the main title as the commit message for all changes, and therefore no obscured balance changes in the main repo. The whole PR itself is also focussed on updating claws and maws, and it's part of that, I just didn't have it in the initial commit for some reason - it really is just a postscript addition that should have already been included.

If it were say changing Sumo range or something, I'd understand the concern moreso, doubly so if it were a complex commit, or one not directly tied to a discussion with Zecrus.  There's no possibility of unrealised changes occurring, and with squashmerge, no such changes remaining labelled as '.' in main repo.  As said though I will try to make minor commit names more verbose in future.

> Given additional thought, would it not be better to just limit the jumping lightning splash damage within the range of the original unit? (Or ensuring that it stays within bounds)
What Sprung said basically, it would add magic force fields and introduce jankery and different behaviour at certain ranges, something we're usually very keen to avoid.

**Comment by WatchTheFort** [comment]
Closing, as "bonus" range overshooting is a feature of weapons in the game, e.g. plasma shells shot at the edge of their range do AoE damage in the bonus range.

**Pull request closed without merging**
