### PR TITLE
Tweaks and improvement to declutter defense-ranges

### PR DESCRIPTION
**Pull request by icexuick**
And removal/integration of old defense-ranges + anti-ranges into new gl4 defense-ranges.

This is a new and tweaked version of the Defense-Ranges Widget.
It is meant to replace the old Defense Ranges.

What needs to be checked but also **fixed/added** is this:

**gui_defenserange_gl4**
1. Show the range rings on mouse-hover on the minimap.
2. Add underwater weapons (torpedoes) as blue rings
3. Make cannon (LRPC) range rings disappear on distance (anti-nukes works correct, cannon does not - it remains visible)
4. Add different pulsating color/fade to anti-nukes (allied) that have 0 stockpile - code of `gui_anti_ranges.lua` should probably be merged into `gui_defenseranges_gl4.lua`

**gui_attackrange_gl4**
1. Separate "cannon" to only LRPC - (only for cannons that shoot over f.e. 2000 range - now it's gets assigned to practically all plasma cannons)
2. Consider adding blue underwater weapons here as well
3. Be able to manually choose which units show firing arcs, and which don't - some have quite some overlapping/confusing arcs which should be removed - while others (like `armmanni` or `cormart`) visually explain their firing-arc very well, and not too cluttering)
5. LRPC now actually show their range on hover because of separate "cannon" settings (only needs to be added to minimap for ideal solution)

New zoomed out view with added LRPC cannons (yellow/orange) and anti-nukes (light-blue)
image

New zoomed in view on defense ranges with much less clutter:
image

PS. Also added as much Legion defenses as possible - but needs checking.

### CODE REVIEW

**Comment by WatchTheFort** [comment]
Old widgets can be deleted, no?

**Comment by Ruwetuin** [comment]
delete the old ones and rename the new ones so they have the same name as the old ones. 

Do this so they get enabled right away, currently only the defaults change and there wouldnt be a change for everyone except completely new players

**Comment by icexuick** [comment]
> Old widgets can be deleted, no?

Well only if Floris or Beherith can add the anti-ranges functionalities inside the new defense-ranges-gl4.

**Comment by icexuick** [comment]
> delete the old ones and rename the new ones so they have the same name as the old ones.
> 
> Do this so they get enabled right away, currently only the defaults change and there wouldnt be a change for everyone except completely new players

Hmm that sucks a little, but indeed I strongly prefer this gets auto enabled over the old widgets.
Do you have some time to help me fix some of the remaining issues?

**Review by WatchTheFort — APPROVED** [review]

**Comment by WatchTheFort** [comment]
After this is merged and we're happy with it working, we should delete the old widgets and rename the new widgets to the old names

**Comment by icexuick** [comment]
There are some remaining issues with correct ranges and weapon types.
And we need a good solution for LRPCs
So it's not yet ready.

**Comment by icexuick** [comment]
@Ruwetuin One question.
Do you know why Juno shows a range ring on its weapon of like 2000-2250 elmos - it should have 32000 range

**Comment by icexuick** [comment]
@Ruwetuin second question - does the cmdcolors_icexuickt.txt still get used?

**Comment by Ruwetuin** [comment]
> @Ruwetuin One question. Do you know why Juno shows a range ring on its weapon of like 2000-2250 elmos - it should have 32000 range

no, but isnt 2000-2250 some max range set in the widget somewhere?

**Comment by icexuick** [comment]
> > @Ruwetuin One question. Do you know why Juno shows a range ring on its weapon of like 2000-2250 elmos - it should have 32000 range
> 
> no, but isnt 2000-2250 some max range set in the widget somewhere?

I have tried to find it, but no luck at all.
Fixed all mines and mostly happy with current state.

**Comment by icexuick** [comment]
For now keeping the old defense_ranges - since that one seems to be more accurate/in-line with the new attack_ranges_gl4.
@Beherith it would be great if you could look at differences between attack-ranges and defense-ranges - specifically near mountains/height changes

**Comment by icexuick** [comment]
Latest update is that it will be very hard to unify both attack/defense ranges.
The biggest issue of differences is when hovering over an enemy defense f.e. - by default it will show it's stencilled defense-range, but on hover it will add the attack-range rings, which are slightly different.

We can 'solve' this by not showing attack-ranges on enemy-defenses - only display these on mobile units f.e.
Even without this, this PR is a big de-clutter/improvement .

If @Ruwetuin or @Beherith could help me with f.e. disabling showing attack-range rings on enemy defenses, then I think it's good to go!

**Comment by WatchTheFort** [comment]
@icexuick What is the status of this? Is it ready for review? Ready for merging?

**Pull request merged**
