### PR TITLE
Fix "length" typo in settings string (and some variables)

### PR DESCRIPTION
**Pull request by peppy**
Just something noticed in passing. I haven't got a full development environment setup currently so cannot 100% confirm the variable changes (still slowly learning the codebase) but it looks like it should work.

In case there is an issue with certain variable changes (wasn't sure about whether `UnitSuffixLength` is used externally, but I've searched across github and it looks quite safe), 7a43811b6 alone solves the typo for the user-visible case and the second commit can be discarded.

### CODE REVIEW

**Comment by Beherith** [comment]
The ones outside of modinfo.lua are sensible, however modinfo.lua needs to be synchronized with the chobby version. Perhaps @Damgam  could look at that one. The rest looks good to me.

**Comment by Beherith** [comment]
Oh and welcome to BAR, peppy!

**Comment by WatchTheFort** [comment]
Since the modoptions change is only to the description, and not the key name, it is fine to merge. The Chobby modoptions.lua should still be updated as the files should be kept in sync.

**Comment by peppy** [comment]
Thanks for the info! I've opened up a PR on chobby to synchronise the change.

**Comment by Beherith** [comment]
Thanks a million dude!

**Pull request merged**
