### PR TITLE
Make all commanders uncapturable

### PR DESCRIPTION
**Pull request by SethDGamre**
Watch the Fort asked me to make this PR to make commanders and commander variants uncapturable. 

There are uncommon cases where commanders are captured which isn't desirable. An example is the Scavenger Boss capturing a Commander instead of killing it.

Also, Decoy Commanders are rendered uncapturable at the discretion of Watch the Fort. I assume because otherwise you could just "capture" a group of decoys with a commander in their midst and the one you can't capture is the real deal. So. It's affected too.

What isn't affected are the scavenger bosses. They remain capturable until I'm told otherwise.

### CODE REVIEW

**Comment by WatchTheFort** [comment]
Has this been tested in-game?

**Comment by sprunk** [comment]
sounds like a good thing to autogenerate from `iscommander`

**Comment by WatchTheFort** [comment]
> sounds like a good thing to autogenerate from `iscommander`

You mean in alldefs_post? For static values like this, don't we want those in the def files, so they're actually WYSIWYG rather than "Why is the value in the def file not the value in the game?"

**Comment by sprunk** [comment]
Don't keep it in the def and make the def take precedence if somebody puts it there.

**Comment by SethDGamre** [comment]
> Has this been tested in-game?

I added the unitdef entry to the armada commander, loaded up the game, tried capturing it. Not capturable. Tried capturing another commander that wasn't given the def, is capturable. Then did a search function for capturespeed and found all the commanders and commander variants that way.

I didn't test every single commander because at the time I didn't see it as necessary for such a simple change. But, I will if I'm asked to.

**Comment by SethDGamre** [comment]
> Don't keep it in the def and make the def take precedence if somebody puts it there.

What's the advantage of generating in post? 

Wouldn't this confuse the hell out of people wondering why commanders aren't capturable yet don't have the capturable = false unitdef?

**Comment by sprunk** [comment]
The advantage of posts is avoiding inconsistency where somebody forgets to copypaste an identical change to one of 50 files, or if a new commander type is created.

The possibility of confusion is always there with any kind of default, but "commanders arent capturable by default" sounds like reasonable rule BAR devs would expect. I think it's a positive tradeoff but you can of course disagree.

**Comment by SethDGamre** [comment]
> The advantage of posts is avoiding inconsistency where somebody forgets to copypaste an identical change to one of 50 files, or if a new commander type is created.
> 
> The possibility of confusion is always there with any kind of default, but "commanders arent capturable by default" sounds like reasonable rule BAR devs would expect. I think it's a positive tradeoff but you can of course disagree.

I have been frustrated in the past by spring wiki and recoil wiki entries that supposedly change the behavior of a thing instead being overwritten by gadgets elsewhere besides the unitdef. Personally I prefer the approach I've already taken, but, I defer to my better's judgement.

I would have to figure out how to execute your approach. As is, I have a good deal of confidence I got all the commanders. If any edgecases come up it'll be a quick fix and I'll be happy to do them.

**Comment by WatchTheFort** [comment]
> The advantage of posts is avoiding inconsistency where somebody forgets to copypaste an identical change to one of 50 files, or if a new commander type is created.

That's what def baking is for: develop & test in _post files, use def baking, push changes to def files. Unfortunately def baking has been completely broken for a long time.

**Review by WatchTheFort — APPROVED** [review]

**Pull request merged**
