### PR TITLE
Comdrop throttle

### PR DESCRIPTION
**Pull request by TheSilverHornet**
### Work done
Slows T1 transports carrying commanders by an additional 0.3, meaning they're about half speed of unladen transports
This factor can be changed by tweakunits also.

Transports also increased somewhat in cost and buildtime, making them more of a strategic choice rather than required taxi service for opening stage of the game.  Rushed transports become increasingly harder to output compared to figs, meaning opponent air can punish flying coms much more easily, compounding with the slower speed.

Overall this should hopefully obligate a change in the air/map meta back towards something more varied.

### CODE REVIEW

**Comment by WatchTheFort** [comment]
It feels like we keep slapping bandaids on top of bandaids for Commander + transport interactions, because there are two diametrically opposing goals that we're trying to satisfy.

**Comment by TheSilverHornet** [comment]
I mean short of making commanders less powerful when used in forward roles, I don't see much other choice here.  This option also lets people change it in lobby if they strongly prefer something else (potentially even map specific)

**Comment by WatchTheFort** [comment]
> This option also lets people change it in lobby if they strongly prefer something else (potentially even map specific)

Please no map-specific game mechanics, we want to reduce the almanac effect, not increase it.

Where is the option part, it looks like these code changes aren't optional?

**Comment by TheSilverHornet** [comment]
I have no plans to do such, but people might decide that map X shouldn't have comdrops, as they currently do with tweaks. This allows that in a less nuclear fashion.

If you add a customparam to a commander with 'transportspeedmult=0.6' for example, then coms will be even slower.

**Pull request merged**
