### PR TITLE
Cluster munitions weapon behavior

### PR DESCRIPTION
**Pull request by efrec**
### Work done

New weapon behavior (not integrated w/ custom weapon behaviors) for cluster grenades and shrapnel munitions that explode on impact, rather than as an airburst.

The behavior assumes a collision so tries to scatter its sub-projectiles according to a few constraints. Cluster munitions applied with the `bouncing = true` customparam additionally avoid re-impacting a target early, instead adding more scatter so they have room to bounce around.

Written for use with the legcluster, the Legion-equiv Gauntlet/Agitator. Sample corpun file included (do not merge) with starfall-stlye projectiles.

### CODE REVIEW

**Comment by efrec** [comment]
lite demo of bouncing on very large, terrain-like units:

https://github.com/beyond-all-reason/Beyond-All-Reason/assets/103912894/d49c0f91-4e98-4f46-9dfa-765627662298

**Comment by efrec** [comment]
This is part of 2999 and awaiting approval over there.

I changed the amount that units deflect away cluster munitions with `bounce = true` and put it in a spreadsheet:
https://docs.google.com/spreadsheets/d/1TPMYXonTFHqoAdKQLAxwGFpvvhJqvHap5eB_ErOdGKY/edit?usp=sharing

As it stands, small chaff units do a pretty good job of absorbing cluster munitions while larger ones tend to spread them around instead of taking direct hits.

**Comment by efrec** [comment]
There's other work to do w/ this, some of which might delay approval.

For polish: Extra DPS of cluster projectiles is not known to the AI nor shown in the GUI.

For balancing: The amount of terrain and unit avoidance can be tuned. If cluster projectiles are too floaty/unreliable to hit, their projectile gravity can be increased.

For the future: Other weapon types can be added. Lightning and fire grenades are doable, and I could see a homing missile swarm or something similar replacing the Juno in a rework.

**Comment by Zecrus2** [comment]
Changes have been included as part of PR2999

**Pull request closed without merging**
