### PR TITLE
Gridmenu home page, gridmenu multi-builder handling

### PR DESCRIPTION
**Pull request by thehobojoe**
### Home page
When a builder is selected, gridmenu no longer displays all the build options (with nonsense sorting) and a paginator. Instead it shows a *column sorted* grid of the first three buildoptions from each category, aligned with the category button. I am calling this the "home page"

image

This is both to provide a stronger hint to the user as to the purpose of the category buttons, but also to make the options shown while no category is selected more relevant, instead of pointlessly showing things like metal/energy storage on the first page. The home page will no longer have pages, to see all the build options the user must enter a category.

### Multiple builder support
When multiple builders are selected, instead of jumbling together all the build options in a confusing mess, now there is an *active* builder whose build options are displayed with the same order and structure as usual, and a small UI to switch between active builders if you want access to other build options. Notably this works with factories as well as constructors.

image

The hotkey is exposed as the action `gridmenu_cycle_builder` and can be bound to anything.

### Back button
To help communicate to the user that they are within a category and need to "go up" to access more build options, there is a new "back" button and keybind hint (on shift, but esc also works).

image

### Other Changes

- Disabled units now always show, but greyed-out and with no hotkey support
- Geothermals are now disabled on maps with no geo spots
- Unit sorting behavior was completely overhauled, so some second-page options *may be in different orders than before*
- Added defined sorting to the t3 labs

### Code changes

- Completely rewrote grid placement logic. Has some comments now to explain what is happening. All the grid placement logic is now in `gridmenu_config` and is accessed through single function calls.
- Broke out basic unit sorting and unit categorizing behavior to `unit_buildmenu_config`. This also handles restrictions of water and geothermal units. This allows a lot of code unification between gridmenu and buildmenu.
- Very heavy cleanup and general refactoring

### CODE REVIEW

**Comment by thehobojoe** [comment]
@badosu I know there's a lot here but I would love a review if you have time

**Comment by aldrenean** [comment]
I like the redesign a lot! I did some testing (non-comprehensive) and I like the way it works.

I do think that your changes actually make the top bar, where the next page/back buttons are, rather unnecessary: is it feasible to replace the categories display with those buttons while we're in a category? It already didn't make sense to show the categories when we were already in a category, and now they're not pressable at all as the layout changes have filled z-x-c-v with units on all categories. Hotkeys that aren't currently active shouldn't be displayed, and using that same area for both the categories and the next page/back button seems sensible and would reduce the vertical real estate of the grid menu.

**Comment by thehobojoe** [comment]
> is it feasible to replace the categories display with those buttons while we're in a category?

Maybe... I'd still want some kind of in-UI indication of which category is currently selected, and a simple implementation of this idea would probably make that impossible. With some good design both may be possible, I will give this a think. If you're able to make more fleshed-out examples that would help me a lot 🙂 

> Hotkeys that aren't currently active shouldn't be displayed

Agreed. I think I can make a quick fix to this particular problem in this PR without any big overhauls.

Thank you for reviewing!

**Comment by thehobojoe** [comment]
Updated category buttons to hide hotkeys during selection, as well as better dimming/highlighting to make the current category visually clear 
image

**Comment by resopmok** [comment]
Tested a couple iterations over the last few days, think we're in a bug-free, nice looking with these changes. The graying of unselected categories is a very nice touch, and I think it now uses expected click functionality according to various feedback (need for a back button, deselect when dropping to home page, not autoselecting buildoption on click for category selection). Very thorough and nice work! LGTM.

**Comment by thehobojoe** [comment]
Thank you for your thorough testing as always!

I also tested in multiple MP games and ran into no bugs, still hoping for at least a cursory code review by someone before asking for a merge.

**Pull request merged**
