### PR TITLE
Extracted quick placing/upgrading functionality from cmd_area_mex

### PR DESCRIPTION
**Pull request by simeonpfeiffer**
Split cmd_area_mex (extracted right click functionality for building/upgrading). Shared behavior is provided by an additional helper widget.

This commit is in preparation to add additional functionality to cmd_rclick_quick_build.lua.

### CODE REVIEW

**Comment by simeonpfeiffer** [comment]
I believe extracting the functionality in itself is a worthy change. If only, so people can disable it without disabling the area mex command.

The suggested additional functionality for geothermal will go into a different pull request.

**Comment by badosu** [comment]
Code looks good to me, I assumed you tested it in multiple scenarios correct?

I'll give it a try and will be good to go for me if no issues

**Comment by simeonpfeiffer** [comment]
The code is basically the same, just split into multiple files and coordinates are now unified (.x, .y, .z instead of both .x, .y, .z mixed with [1], [2], [3]).

I tested it on regular maps and metal maps and couldn't find any issue.

**Comment by Beherith** [comment]
Sorry for the lateness, but I tested this PR and noticed and interesting side effect. Select a constructor, and right click on any other unit or structure, and it will go and build the nearest empty mex instead of guarding :D

**Comment by simeonpfeiffer** [comment]
Oh wow, I never thought of that. I will fix this later! :)

**Comment by simeonpfeiffer** [comment]
Sorry for the oversight, should work as intended now.

**Pull request merged**
