### PR TITLE
Legion atlas beautification + other small fixes

### PR DESCRIPTION
**Pull request by Tharsy**
### Work done
- Some extra animation + lighting improvements for legsrail and legrail
- Improved the fidelity of the legion texture atlas v7
- Anim fix for legmlv
- Updated model for legcv
- New Model: Goblin created by Odin
- New Unit: Heavy Drone (Added to evocoms)

### Issues
- ~~legion atlas normal is uncompressed, not sure what to do about it without compression making it look horrible.~~

### Work needed
- ~~Help for correctly configuring unit stats/weapons (Separating g2g and g2a railguns)~~ This can wait as it might need some black magic to get it working but bos code / lighting is in place

### CODE REVIEW

**Comment by Beherith** [comment]
@Tharsy could you screenshot me the nvidia dds export UI from photoshop that you are using?

**Comment by Tharsy** [comment]
> @Tharsy could you screenshot me the nvidia dds export UI from photoshop that you are using?
image

And uncompressed u8888 can be fine, I will restrict it to the normal map as that's the file that requires the most precision. if anything :>

**Comment by Beherith** [comment]
@Tharsy Have you seen the command `/reloadtextures s3o`?

**Comment by Beherith** [comment]
> > @Tharsy could you screenshot me the nvidia dds export UI from photoshop that you are using?
> > image
> 
> And uncompressed u8888 can be fine, I will restrict it to the normal map as that's the file that requires the most precision. if anything :>

Ive had better luck with a custom Kaiser filter for mipmaps.

**Comment by Tharsy** [comment]
> > > @Tharsy could you screenshot me the nvidia dds export UI from photoshop that you are using?
> > > image
> > 
> > 
> > And uncompressed u8888 can be fine, I will restrict it to the normal map as that's the file that requires the most precision. if anything :>
> 
> Ive had better luck with a custom Kaiser filter for mipmaps.

I had a look through those the mipmaps are not my issue. even the full quality map looks scuffed when compressed in bc3

**Comment by Beherith** [comment]
Ah yes to continue on, finally mips from command line are fixed!
https://forums.developer.nvidia.com/t/nvtte-2024-1-0-mip-filter-parameters-not-read-from-command-line/291915

**Comment by Beherith** [comment]
I approve this pr 100%
I would like to ask that the WM file + blender file get put somewhere in our artwork repo.

**Review by Beherith — APPROVED** [review]
its good

**Pull request merged**
