### PR TITLE
Add mechanism for sending synced->unsynced map point messages.

### PR DESCRIPTION
**Pull request by saurtron**
### Work done

Added a mechanism to send luarules messages from synced to unsynced allowing for unsynced handling of map points/mapmarkers.

- Uses 'mppnt:{jsondata}' payload and sends to global Script.LuaUI.MapPointEvent.
- Inspired by the mechanism from game_messages.lua since the goal is similar, just translating/enhancing mapmarkers, not just chat messages.

#### Setup
- Place  [gui_ping_wheel.lua](https://raw.githubusercontent.com/saurtron/Beyond-All-Reason/refs/heads/add-ping-wheel-widget/luaui/Widgets/gui_ping_wheel.lua) and [gui_ping_wheel_event.lua](https://raw.githubusercontent.com/saurtron/Beyond-All-Reason/refs/heads/add-ping-wheel-widget/luaui/Widgets/gui_ping_wheel_event.lua) inside luaui/widgets so you have smth using this.

#### Test steps
- Install ping wheel as shown above.
- You can now use alt+w or mouse 4/5 to show it and place a map marker, it will use the new mechanism.

#### Notes
This paves the way for i18n for the marker texts, as well as lua side rendering, or completely skipping engine support and just managing it from lua.

Might be better to use a widget callin instead of global, but did it like this to not overcomplicate for now.

I'm pr'ing this first since then the rest of ping wheel work can be tested with just widgets in luaui/widgets, so no need for custom BAR. This part is needed since otherwise there's no way to send synced message that will result in each client rendering different text on markers (each player will see it in their own language).

### CODE REVIEW

**Comment by sprunk** [comment]
Use `Spring.SendLuaUIMsg` instead of going through luaui -> luarules(synced) -> luarules(unsynced) -> somebody else's luaui.

**Comment by saurtron** [comment]
I think we need this because the idea is to send the map marker to everyone so they can render it in their own way (internationalized).

Workflow is send map marker from widget->gets synced to everyone->they render it in their own game with i18n and maybe local customizations.

**Comment by sprunk** [comment]
Yes, that's what `Spring.SendLuaUIMsg` does except it doesn't go through a bunch of unrelated states.

**Comment by saurtron** [comment]
Ok, sorry thought you meant it had to be unsynced->unsynced on the player own gui. If LuaUIMsg syncs to all players then I guess that's much better :D

**Pull request closed without merging**
