### PR TITLE
Part2 reclaim highlight fields

### LINKED ISSUE #3419: metal reclaim widget lags the game
### Description

https://i.imgur.com/GLWJlMU.jpeg (imo this isnt a lot of wrecks and should be smooth)

When you have a lot of wrecks on the ground it becomes a lag machine, it seems to recalculate the metal on ground quite often like once per sec, this could probably be changed to say 2-3 secs without impacting the experience, maybe even calculate it once just when you click a reclaimer unit like rezbot instead of constant updates.

Also the way it calculates metal on ground seems too expensive.

Possible lag fix for this? Make the metal calculation more efficient causing less lag?

### Expected Behaviour

Smooth experience.

### Actual Behaviour

Lag hiccups every second, fps drops.

### Reproduction steps

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by efrec**
### Work done

Refactor of existing clustering algorithm into the same method but without several generalizations used in OPTICS that don't apply to this use case. This is now a basic single-chain reachability clustering method.

The extent of the rewrite puts this in a category that it likely needs testing before merge.

I precondition the candidate points for the convex hull makes hulls build in about the same amount of time no matter how large they are. My testing on 1600 wrecks shows essentially no impact at all from the convex hull step, as a result.

Some better-practices on OOPish code, mostly avoiding a lot of copying.

Cold starts were the topic I wanted to address, where clustering done for the first time creates a large frame hitch. This is, again, only a portion of the way to fixing that problem. The tables used for clustering are built over time so that all O(N^2)-ish work is done in O(N) chunks on each FeatureCreated and O(logN) on FeatureDestroyed. The remaining final clustering step significantly faster as a result.

#### Addresses Issue(s)

This PR could be considered to close #3419 if there are no bugs. The gains are good enough.

This is not an iterative clustering method, still. Maintaining a clustering that is almost-correct over time would be much faster and is a good further goal for the widget for the compsci-inclined.

### CODE REVIEW

**Comment by efrec** [comment]
Pretty fast.

https://github.com/user-attachments/assets/37bc2b9c-25be-49c8-9bca-0058c0220538

**Comment by sprunk** [comment]
Those corner rocks get excluded at the end of the video, why?
image
image

**Comment by efrec** [comment]
Fixed. I had added a process that finds a XZ-aligned rectangle for culling points that is (supposed to be) inscribed inside the set of cluster points, like so:

image

There were cases that wasn't followed:

image

Caused by extreme points that should have updated multiple bounds, instead only updating one. Next commit allows multiple updates, and made the expansion of the quad a little more stable by seeding a start point closer to the center. There isn't really a perf hit to do so and debugging is kinder when the order is semi-similar between runs.

**Comment by efrec** [comment]
I think this is good to go. Some last change notes:

To make it less erratic, I reduced the update frequency (2/sec), brought the min and max font sizes a little closer together, and made the font label's position less sensitive to change. The text jumps around a lot less.

**Review by efrec — COMMENTED** [review]
I really did not, no. It just became my preference at some point, especially to check for explicit nil or false. Should I change those back, then? Not an issue to me.

**Pull request merged**
