### PR TITLE
Steal tint, glow, and rescale from ZK

### PR DESCRIPTION
**Pull request by sprunk**
Lets modders apply visual changes via tweakunits/tweakdefs. Also has a GG interface.

image

image

### CODE REVIEW

**Comment by Beherith** [comment]
Im afraid this is not a rendering approach that fits with the BAR GFX pipeline, and does not scale at all.
This kind of tint + xray must be done with CUS GL4 and SetUnitUniformBuffers.

For details, see how Raptors are tinted.

**Comment by sprunk** [comment]
This is for tweakdefs modding so I'm not sure how much worry scaling is given what you can do with modoptions. I'm absolutely incompetent at graphics though so the most I can do is remove the GG interface so people developing the base game don't feel tempted to use it.

**Comment by Beherith** [comment]
Was there a specific request from tweakdefs modders for this kind of functionality? Or is this just intended as a future way of 'marking' units that have been tweaked? 

Id like to avoid introducing functionality to modders that:
1. Is highly suboptimal from a performance perspective
2. Breaks on damaged units (vertex displacement), and does not improve looks, 
3. I dont want to maintain going forward.

**Comment by sprunk** [comment]
> Was there a specific request from tweakdefs modders for this kind of functionality?

https://discord.com/channels/549281623154229250/858397131148623892/1153004894345768981

> Or is this just intended as a future way of 'marking' units that have been tweaked?

This is primarily a simple way for modders to customise visuals via tweakdefs (since you can't change model or script that way). Maybe if you change a unit to be EMP you make it glow blue to convey this. Or if a unit is changed to be more powerful it also becomes bigger. This isn't just "marking" in that you can convey something useful about the unit, or differentiate two versions of the same tweaked unit.

Down the road, when modding supports gadgetry (as opposed to just tweakdefs) you could use this API do things like make tint affected by acid green, or make buffed units glow. By that point somebody may come up with a nice GL4 solution though so this part isn't that important.

> Is highly suboptimal from a performance perspective

It's a valid concern but I think as long as you can do things like set metal mult to x100 or change berthas to have 0.03s reloadtime then trying to make mods performant is a bit of a lost cause.

> I dont want to maintain going forward.

I'm not sure if it needs any maintenance, it's crude/simple enough that I wouldn't expect it to break. So perhaps it could just sit there. If it does break then at worst you can just get rid of it, the basic interface is just a customparam so a removal of the gadget will always be clean (no crashes etc, there will just be nothing to interpret it).

---

In general the desireable feature here is to have a way to tint and rescale units, configurable via customparams for tweakdefs. It doesn't have to be this specific implementation and I agree it would be ideal if there was GL4 solution which was performant/scaleable/maintainable/etc. ZK just happened to have something that a BAR modder requested so I made a copy-paste PR to make it available, but I am not that interested in rewriting it.

**Comment by drivver44** [comment]
does the rescaling of units affect the hitboxes or aimpositions of the unit(s) affected?

**Comment by sprunk** [comment]
Affects mesh-derived things. Hitbox is up to the modder but it sounds east to rescale it too if need be.

**Comment by sprunk** [comment]
Feel free to steal if you change your mind.

**Pull request closed without merging**
