### PR TITLE
chore(chat): Lint stuff

### PR DESCRIPTION
**Pull request by badosu**
This was supposed to be part 1 of feature request to use s (spec) a (player) as initial input mode.

Since that was already met I'm sending it as a standalone.

### CODE REVIEW

**Comment by Beherith** [comment]
Is the performance cost / perception overhead of unused widget:Callin(args) being accepted and not used that much greater than the clarity of actually having them there for 'future reference'? 

Even more so for _ unused vars?

I'm genuintely curious, because I tended to go the full opposite of this linting direction.

**Comment by badosu** [comment]
I don't know, I just lint stuff. I'll reopen if desirable, I'll apply my standards to my own code next time.

**Comment by badosu** [comment]
The undefined globals and the legacy undefined/unset variables should be addressed in some way or another though.

**Comment by Beherith** [comment]
Oh man, didnt even realize there were undefined globals, you mean the ones fixed in 
```
local topbarArea
local addedOptionsList
local scrolling -- FIXME: never assigned, still used by internal logic
```

Yeah those are bad, littering global namespace if never used.

**Comment by Beherith** [comment]
I'm totally fine with other coding style btw, and I dont really care either way as i'm not the maintainer of this widget

**Pull request closed without merging**
