### PR TITLE
The Big Legion Makeover: Strategic Icons, Batch 1

### PR DESCRIPTION
**Pull request by ZephyrSkies7**
### Work Done
- Updated napalm strategic icons to use a flame icon inside the shells to better convey napalm capabilities from a glance.
- Added a laser tank strategic icon, which the `leghelios` aka Helios now uses.

### CODE REVIEW

**Comment by icexuick** [comment]
I want these to be added in the main Figma file with all the strategic icons, so they all live in one place.
I'd like to see in-game shots for these icons, preferably with comparisons with old.

The size of the icons/bombs/shells is picked/set for reasons.
I'd also like to keep the consistency, unless convinced by comparison screenshots that the new ones are better.

**Comment by icexuick** [comment]
Also the quality on the new icons seems to not be sharp/clean.
For optimal quality I think its wise / needed to have them be as clean/crisp as possible.

**Comment by ZephyrSkies7** [comment]
> Also the quality on the new icons seems to not be sharp/clean. For optimal quality I think its wise / needed to have them be as clean/crisp as possible.

I don't have the original files so I was making do with the PNG files included in the game :) they are in the figma I presume?

**Comment by ZephyrSkies7** [comment]
> I want these to be added in the main Figma file with all the strategic icons, so they all live in one place. I'd like to see in-game shots for these icons, preferably with comparisons with old.
> 
> The size of the icons/bombs/shells is picked/set for reasons. I'd also like to keep the consistency, unless convinced by comparison screenshots that the new ones are better.

Screenshots incoming in about an hour 🫡

**Comment by icexuick** [comment]
> > Also the quality on the new icons seems to not be sharp/clean. For optimal quality I think its wise / needed to have them be as clean/crisp as possible.
> 
> I don't have the original files so I was making do with the PNG files included in the game :) they are in the figma I presume?

They are in a Figma file called "BAR_strategic_icons"
I hope you already have access, since Figma changed a big thing in sharing files, and currently locked all files.
There are work-arounds (without paying a huge amount of $$$ for each editor) so if you don't have access I will get to that workaround and give you access.

We need these icons to live in one place.
If we ever decide to increase resolution, or global styling or do other mass changes, then having all files in there is a must.

**Pull request closed without merging**
