### PR TITLE
units README for common-name to source-name reference (doc-only)

### PR DESCRIPTION
**Pull request by openyk**
For new/advanced players and developers looking at the units source code, to make it easier to map between the different unit-names vs file-names. 

1. Existing mapping at main website unit URLs mentioned.
2. Single-view list-map example provided with all Armada Bots.

### CODE REVIEW

**Comment by badosu** [comment]
You can reference this file: https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/language/en/units.json

**Comment by WatchTheFort** [comment]
Closing as unit name <-> unit ID mapping already exists in the units.json file, which serves as the source of truth for this information. We should avoid having to maintain the same data in two separate places.

**Comment by WatchTheFort** [comment]
Closing as unit name <-> unit ID mapping already exists in the units.json file, which serves as the source of truth for this information. We should avoid having to maintain the same data in two separate places.

**Comment by openyk** [comment]
I propose that the units readme be updated and merged as a clarifying note for new source code readers who are not aware of the json file, mentioning that and the main website units URLs.

Alternatively, is there a dedicated place like /docs/ for source-code-related documentation?

**Pull request closed without merging**
