### PR TITLE
Misc errors

### PR DESCRIPTION
**Pull request by TheSilverHornet**
### Work done
Tweaked i18n to not -fill- log with false positives about missing translations.

Eg right now I have 457 hits on 'error' and they will almost all be from this one source. It's impossible to debug things.

(also fixed 2 unit portraits that are somehow old versions)

### CODE REVIEW

**Comment by Ruwetuin** [comment]
[t=03:01:50.496885][f=-000001] Error: [LuaUI::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=LoadCode trace=[Internal Lua error: Call failure] [LuaVFS::Include(synced=false)][pcall] file=LuaUI/setupdefs.lua error=2 ([string "modules/i18n/i18nlib/i18n/init.lua"]:150: Incorrect arguments to Spring.Log(logsection, loglevel, ...)) ptop=3 cenv=false vfsmode=Mmeb
stack traceback:
	[C]: in function 'Include'
	[string "--------------------------------------------------------------------------------..."]:24: in function 'chunk'
	[string "luaui.lua"]:50: in main chunk

**Comment by TheSilverHornet** [comment]
> [t=03:01:50.496885][f=-000001] Error: [LuaUI::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=LoadCode trace=[Internal Lua error: Call failure] [LuaVFS::Include(synced=false)][pcall] file=LuaUI/setupdefs.lua error=2 ([string "modules/i18n/i18nlib/i18n/init.lua"]:150: Incorrect arguments to Spring.Log(logsection, loglevel, ...)) ptop=3 cenv=false vfsmode=Mmeb stack traceback: [C]: in function 'Include' [string "--------------------------------------------------------------------------------..."]:24: in function 'chunk' [string "luaui.lua"]:50: in main chunk

Good spot, looks like I'd jumped repos while testing, will investigate

**Comment by WatchTheFort** [comment]
But they are legitimate errors, they should be fixed rather than ignored.

**Comment by TheSilverHornet** [comment]
> But they are legitimate errors, they should be fixed rather than ignored.

I couldn't agree more, but nobody has in the several times I've mentioned it, and it makes logs nightmareish for development work.

I fix the ones I can or are relevant to what I'm doing, but I can't adopt every problem I encounter otherwise nothing would ever move.  Damgam has said some are redundant units, I don't know which they are though.

**Pull request merged**
