### PR TITLE
WIP: Move lua AIs to unsynced

### PR DESCRIPTION
**Pull request by tomjn**
I'm shocked nobody thought to just move the `else` line up the file

Note: Untested, I don't know if DAI or STAI cheated and called synced Spring APIs directly ( if so boooo you didn't need to do that )

### CODE REVIEW

**Comment by sprunk** [comment]
Won't using unsynced API just create a ton of network traffic from everybody which all then gets dropped because none of the players are hosting the bot?

**Comment by tomjn** [comment]
> Won't using unsynced API just create a ton of network traffic from everybody which all then gets dropped because none of the players are hosting the bot?

Possibly, but AIs don't generate a lot of commands unless they're built poorly, at which point everybody would notice wether they're synced or not. This is a crude PR that literally only achieves the goal, it doesn't actually do any of the refinements, like making the AI only run on one machine, or handling any of that. Damgam has already confirmed DAI uses synced APIs in discord, so additional work is needed.

**Comment by Ruwetuin** [comment]
hey, I'm not sure what to do with your / ai pull requests in general, since i m not that informed about its state, inner workings and goals and readiness of these pull requests. Therefore its hard for me to merge it blindly. What do you aim for me to do here?

**Comment by tomjn** [comment]
WIP PR, don't worry I'll poke when it's ready

**Comment by badosu** [comment]
@tomjn Is this something you still wish to work on?

**Comment by tomjn** [comment]
@badosu that would be difficult, I had hoped that the BAR engine would reach a state where I could either run it headless or run it in a low graphics or degraded non-standard state on MacOS, however it now seems that to work with the engine I need to buy a high end Windows PC and splash the cash on a 3000 series card end graphics card lest I be considered a potato and left behind.

Coupled with the fact a lot of basic precursors to unsynced AIs depend on doing things that Trepan did in 2010 to implement lua gadgets but again, yet nobody has bothered to do the necessary copy pasta, and somehow native AI became the new hotness.

Suffice to say it's difficult to drum up motivation and resources.

As an aside, AI isn't just about the opponent in a skirmish battle or compstomp, a lot of opportunity for performance and gameplay improvements is left on the table if you silo all AI stuff to dedicated AI people with such a limited scope.

---

Honestly, if it loaded but had piss poor graphics that required me to build a widget called "shitty user interface" in a mutator that just had plain rectangle buttons, that would be fine, but broaching that subject leads to big grand discussions of why we can't just keep supporting things forever, and prejudiced discussions of MacOS.

**Comment by badosu** [comment]
@tomjn Thank you for closing and providing all context related to your changes, I appreciate

**Comment by pandaro** [comment]
I would always be happy to learn something from af. He is a somewhat tough but very prepared teacher.
Yes maybe the C ++ interface is in vogue, but shard remains a competitive opponent, I work a lot to keep it fit.
I don't have the technical skills nor the time and strength to study enough to finish this pr.

**Pull request closed without merging**
