### PR TITLE
Mex Animation: Use Go() instead of fixGo()

### PR DESCRIPTION
**Pull request by badosu**
Engine sends Go() after SetSpeed() required for properly activating when extraction map changes

All tested, only cormexp, which is too complicated for me, is missing.

### CODE REVIEW

**Comment by KyleAnthonyShepherd** [comment]
Have you tried testing what happens when the mex is EMP stunned?
It looks like fixGo was being used due to some interaction with SetStunned()

**Comment by badosu** [comment]
Yes, I tested and it works as expected.

**Comment by KyleAnthonyShepherd** [comment]
Cool. And I'm not seeing a case where multiple engine-initiated Go calls can stack and cause conflicting animations. So looks good to me.

**Comment by badosu** [comment]
The only place Go is called from engine is when mex has extraction rate changed and unit is activated

**Pull request merged**
