### PR TITLE
hitbox fixes part 2

### PR DESCRIPTION
**Pull request by drivver44**
the collisionvolumes.lua is here because i need to nuke relevant units out of that file. that file overrides anything in unitdefs

### CODE REVIEW

**Comment by sprunk** [comment]
> that file overrides anything in unitdefs

that's the point? why not fix the contents of that file instead

**Comment by drivver44** [comment]
> that's the point? why not fix the contents of that file instead
the file isnt relevant to the 2 units anyways better to remove unneeded code

**Comment by KyleAnthonyShepherd** [comment]
It is partially relevant to armamb. It retracts into an armored OFF state, having a lower profile, so a hitbox update seems reasonable to do when it retracts. 
But its profile does not change that much, and the hitbox may need to be a bit low anyway to make it easier for nearby armamb to fire over each other.

**Comment by drivver44** [comment]
IMO it would be best for as much of the hitbox date to be in the unitdefinitions rather than a 3rd file elsewhere
also Beherith said go ahead for removing unneeded units in collisionsvolumes

**Comment by KyleAnthonyShepherd** [comment]
If a custom unitdef can can handle different hitboxes for ON/OFF states, that would be great, would make it easier to keep unit information in one file

**Comment by drivver44** [comment]
shiva has a custom hitbox for a deploy mechanic that doesnt exist in the game and likely never come to the game
(afaik bar doesnt want deployment mechanics)
its actually safe to remove the custom hitboxes from a number of other units defined in collisionvolumes
the viper com

**Review by Zecrus2 — APPROVED** [review]

**Pull request merged**
