### PR TITLE
vao map_startbox

### PR DESCRIPTION
**Pull request by loveridge**
### Work done

map_startbox.lua updated with VAOs. Updated startbox to have an edge fade effect, and the startposition cones don't blink.
My shader skills are pretty bad, a cooler start position effect would be nice.

image

#### Setup
Take it for a spin by enabling the widget, and disabling the old one.

### CODE REVIEW

**Review by salinecitrine — APPROVED** [review]
This looks great! Tested it out while spectating a couple games and it works perfectly as far as I can tell.

**Comment by ChrisFloofyKitsune** [comment]
the only reason not to just nuke the old widget is because some graphics card bug nonsense may happen

but if that's happening... then there's probably a lot of other fancy GFX stuff broken for them too?

> * keep the old widget, and:
>     * default enable this widget
>     * default disable the old widget
>     * in the new widget Initialize(), check if the old widget is running and disable it if so

this one is the safe route, as much as I want to yeet the old widget into oblivion

**Comment by p2004a** [comment]
Stupid question: If we wanted to support non rectangular startboxes, would all changes be in this widget? Is this the place where you also verify whatever what user clicked is correct location or not?

Requests for non rectangular startboxes pops up often for some maps, especially when they are diagonal.

**Comment by loveridge** [comment]
> Stupid question: If we wanted to support non rectangular startboxes, would all changes be in this widget? Is this the place where you also verify whatever what user clicked is correct location or not?
> 
> Requests for non rectangular startboxes pops up often for some maps, especially when they are diagonal.

I believe most of that is handled by `game_initial_spawn.lua`

**Comment by badosu** [comment]
> Stupid question: If we wanted to support non rectangular startboxes, would all changes be in this widget? Is this the place where you also verify whatever what user clicked is correct location or not?
> 
> Requests for non rectangular startboxes pops up often for some maps, especially when they are diagonal.

Effort would be split in multiple places, most of it would go into the gadget to parse the list of nodes for each start box. Zk has such one, we'd also have to provide a way to edit or at least feed the polygon list into the start script. Finally there would be a ripple effect into this and other widgets for adjustments, for this one the change would be relatively simple, to receive and tender the lost of nodes that comprises each polygon.

**Comment by sprunk** [comment]
If you want to be future-proof you could already treat the current rectangles as polygons:
```lua
local function GetStartbox(allyTeamID) -- returns a polygon: array of vertices
  	local x1, z1, x2, z2 = Spring.GetAllyTeamStartBox(allyTeamID)
  	return {
  		{x1, z1},
  		{x1, z2},
  		{x2, z2},
  		{x2, z1},
  	}
  end
  ```

**Comment by p2004a** [comment]
> we'd also have to provide a way to edit or at least feed the polygon list into the start script

That's fine, startbox format in Rowy is compatible with storing arbitrary polygons and infrastructure to generate and set modoptions per map in multiplayer was deployed for starpos suggestions widget https://github.com/beyond-all-reason/spads_config_bar/blob/main/etc/mapBattlePresets.conf so adding another modoption to pass polygons is trivial.

> Finally there would be a ripple effect into this and other widgets for adjustments

and places like replay site.

But, from infrastructure side, this is fully unblocked IMHO.

**Comment by Ruwetuin** [comment]
edges on/near the map border are enlarged when camera is tilted
2024-08-11 16_26_41-Beyond All Reason (Spring 105 1 1-2572-g7e87fc1 BAR105)

**Comment by Beherith** [comment]
subbed

**Comment by WatchTheFort** [comment]
Is this part of https://discord.com/channels/549281623154229250/1274067162176290860, or is it superseded by that?

**Comment by Beherith** [comment]
This work is superceded by start polygons widget.

**Pull request closed without merging**
