### PR TITLE
feat(gridkeys): Add some bindings

### PR DESCRIPTION
**Pull request by badosu**

### CODE REVIEW

**Comment by badosu** [comment]
cc @resopmok

**Comment by resopmok** [comment]
I would choose something closer in I think, there's plenty open with Ctrl.. maybe ctrl+t since it's also a mnemonic? this would leave ctrl+r open for another custom army selection bind too.

**Comment by badosu** [comment]
> I would choose something closer in I think, there's plenty open with Ctrl.. maybe ctrl+t since it's also a mnemonic? this would leave ctrl+r open for another custom army selection bind too.

@resopmok  Let me know what you consider to be a good solution

**Comment by badosu** [comment]
Switched to ctrl+t

**Comment by badosu** [comment]
Added ctrl+f7 for luaui hide

**Comment by resopmok** [comment]
Yes this lgtm now, can we make it permanent?

**Comment by badosu** [comment]
> Yes this lgtm now, can we make it permanent?

Permanent?

**Comment by badosu** [comment]
Thank you!

**Pull request merged**
