### PR TITLE
 Add Windmill<->Tidal link to Context Build Widget #3340 

### PR DESCRIPTION
**Pull request by nevniv**
Add Windmill<->Tidal link to Context Build Widget #3340

### Work done

Added mapping for wind turbines for all three factions into context build widget

#### Test steps
Tried building wind turbines and solars in the water with all faction coms to make sure they both still created tidals

### CODE REVIEW

**Comment by nevniv** [comment]
A downside of this, as roberttheepie pointed out, is that now that we've mapped two things to tidal, if the widget converts to your wind to a tidal and then you move your cursor back to land, it's going to turn into a solar on land.  I don't think there is any getting around this.  The alternative is winds just don't convert at all like today.

**Comment by WatchTheFort** [comment]
This creates a problem in the following situation:

1. Wind selected to build on land near coastline
2. Mouse drifts over water, changes to tidal
3. Mouse moved back over land, switches to solar

Can this be implemented so that when multiple buildings map to the same water unit, the context is remembered to always swap back to the original one?

**Comment by robertthepie** [comment]
> Can this be implemented so that when multiple buildings map to the same water unit, the context is remembered to always swap back to the original one?

This turns out to be too much for nevniv/totermann per conversation in the discord

Looking at the widget, the current data structure is probably not ideal for such a concept.
If it was a simple `a` changes to `c` and `b` changes to `c` we could set to `c` changes to whichever switched to it last.
But instead the widget itterates over its list of ground and sea units to see it if found the current unit, and returns its position in the array, which in my opinion seems far from ideal as it itterates over the list of all switchable units a lot, and also means that duplicate entries aren't acknowledged.
so when i have some time i'm going to take a look at the past versions based on the "Rebuilt" part in the creddits, and take a look at switching the underlying data structure.

**Comment by nevniv** [comment]
As noted above, I can update a table but I don't know how to rewrite the widget's logic which is being asked for.
badosu made some suggestions on Discord as to how to implement. .which I attempted to put in some kind of pseudocode in comments to give someone an idea of what I thought might work but I have no idea.

**Comment by nevniv** [comment]
_I surrender
To the strawberry ice cream_

**Pull request closed without merging**
