### PR TITLE
Laundry list of small bugfixes

### PR DESCRIPTION
**Pull request by TheSilverHornet**
### Work done
Removed unused *carry2 buildpics
Updated junos to affect legion scouts
Shockwaves now autocloak, and have water impact sound effects
Siegebreaker default weapon altered
Submarines retagged
Legsolar updated to new atlas (far harder than it sounds)

### CODE REVIEW

**Comment by ZephyrSkies7** [comment]
Do Scavengers not spawn `armcarry2` and `corcarry2`?

**Comment by Damgam** [comment]
These are a thing? We figured out with Hornet with the last messed up pull request that they don't exist.

**Comment by ZephyrSkies7** [comment]
> These are a thing? We figured out with Hornet with the last messed up pull request that they don't exist.

I thought these were the old haven and oasis after the new ones got new models/roles. If Scavs dont spawn them that means they really don't exist.

**Comment by TheSilverHornet** [comment]
> > These are a thing? We figured out with Hornet with the last messed up pull request that they don't exist.
> 
> I thought these were the old haven and oasis after the new ones got new models/roles. If Scavs dont spawn them that means they really don't exist.

they were, but are no longer. if you can find them in codebase please let me know, but they seemed purged, at least by that name

**Pull request merged**
