### PR TITLE
The Big Legion Makeover: Pharos Added

### PR DESCRIPTION
**Pull request by ZephyrSkies7**
### Work done
In replacement of the Cortex Guard, the **_Pharos_**, a _Light Heat Ray Tower_, has been added.

#### Addresses Issue(s)
Replaces placeholder Cortex Guard with original Legion unit.

#### Needs Fixing

- [x] The Legion wreck texture atlas, as well as damage shader, needs to be fixed before this unit is ready to add to the game.
- [x] The unit still needs to be balanced properly by Zecrus before this unit is ready to add to the game.

#### AFTER:
image
image
image
image
image
image
image

### CODE REVIEW

**Review by ChrisFloofyKitsune — CHANGES_REQUESTED** [review]
You probably didn't meant to include the "output" folder?

**Comment by ZephyrSkies7** [comment]
> You probably didn't meant to include the "output" folder?

No I did not lol thanks

**Comment by Beherith** [comment]
@ZephyrSkies7 @Zecrus2  did you, at any point while testing this encounter error spam from the DrawUnitGL4 API?

**Comment by ZephyrSkies7** [comment]
Error spam? No, I didn't receive any errors at all during local testing. During live-game testing I received an error message regarding weapondef table of sorts? Only with the Pharos and only at the beginning of the game when one is made for the first time.

**Pull request merged**
