### PR TITLE
Create dbg_engine_shader_reload.lua

### PR DESCRIPTION
**Pull request by Beherith**
#### Test steps
- [ ] Write the steps needed to test out the changes. Include the expected result.

### CODE REVIEW

**Review by saurtron — COMMENTED** [review]
Tried the widget and seems to work fine! Thx for making this, very cool!

Made a couple minor remarks on the code too.

**Comment by saurtron** [comment]
Oops sorry intended to just make comments, not review and block anything.

**Comment by Beherith** [comment]
Gettimers is the standard way in Recoil, we try to avoid os.clock(). Fair on the first point though

**Comment by saurtron** [comment]
> Gettimers is the standard way in Recoil, we try to avoid os.clock(). Fair on the first point though

In this case it won't make a difference, but I believe os.clock() overhead must be much lower than calling those methods.

I think those can be warranted when you need more resolution. Maybe I'm being a bit paranoid but have to take into account lua has limitations c++ doesn't have, also my pov is every little bit counts when not sacrificing clarity, and in this case the method of calling the engine to get seconds is a bit convoluted tbh (2 calls into engine when the other method is just 1 lua call and substract opcode). Anyways sorry if nitpicking too much XDD I won't bring this up any more.

**Comment by sprunk** [comment]
A comparison with pros and cons of `Spring.DiffTimers` vs `os.clock` would be good to have somewhere

**Comment by Beherith** [comment]
It's mostly out of habit, I doubt the perf is much different on them. Probably 50 vs 100 nanosecs or something

**Comment by sprunk** [comment]
Not just a perf comparison though, also behaviour details like vulnerability to float accuracy issues or somebody setting the clock backwards (daylight savings time happening midgame?). I assume `Spring.DiffTimers` is superior (or at least not worse) on most relevant counts but it would be good to have an expert confirm. I barely ever use either of those so wouldn't know, but it would be nice info to put in `DiffTimers` API docs

**Comment by Beherith** [comment]
Iirc spring_time objects are 64 bits underneath, so float over/underflow are less of an issue. Difftimers allows for microsec resolution. However the difftimers returns a 32 bit float, which for example after an hour of game time, is sometimes borderline.

**Comment by Beherith** [comment]
E.g. after 3600 seconds, you are down to millisecond levels

**Comment by saurtron** [comment]
I did a small benchmark with 100000 calls, getting a=currtime, b=newtime-currtime, with both methods:

The differences are pretty negligible, but I also tested for calling with local speedups, that has a greater impact. Nothing to worry about but I think it's interesting specially note the local speedups have the biggest impact.

| time (ms) | method |
| --- | --- |
| 11 |  os.clock |
| 8.5 | os_clock |
| 15 | Spring.GetTimer and Spring.DiffTimer |
| 10 | spGetTimer and spDiffTimer |

Anyways my main concern is that os.clock usage is more idiomatic and straighforward to use.

Regarding functionality I think they both measure non-timezoned time so shouldn't be an issue with summer time change, not sure if user changes the computer time while playing manually in some other way would be interesting to test.

In any case, I guess none of those are safe to use for synced code, since they provide current time for the user computer. For simple cases like measure a few seconds have passed it shouldn't make much of a difference tbh.

I think the GetTimer stuff makes sense for portability, higher resolution and consistency inside the c++ code, not sure about the use case for lua, but maybe when you want to coordinate with the engine using it's same time structures without float errors, or you want higher resolution than os.clock gives.

Anyways, guys, we're going too far with this XDD

**Comment by petersarkozy** [comment]
> Probably 50 vs 100 nanosecs

Spot on :D

**Pull request merged**
