### PR TITLE
Select com reapplies if only 1 com

### PR DESCRIPTION
**Pull request by K0NQUEROR**
### Context
Previously when using select commander hot key it would always focus the camera on the commander. Recently it stopped working if you only have 1 commander. If your 1 commander is selected it does not focus the cam on it when using selectCom.

### Work done
Updated logic to allow reselecting singular commanders.
If you only have 1 commander it will be added to the list of selectable commanders, as a result it is reselected and focused.

#### Test steps
Tested in dev with 1 commander and multiple. Successfully swaps to different commanders with comSelect and always centers if only 1 com, even if it is currently selected.

### CODE REVIEW

**Comment by sprunk** [comment]
Change your binding from `selectcom` to `selectom focus`?

cc @badosu

**Comment by K0NQUEROR** [comment]
> Change your binding from `selectcom` to `selectom focus`?
> 
> cc @badosu

I use legacy which has `selectcomm focus`. In that loop I edited, it prevents the reselection of already selected coms. Which as a result does not refocus your cam if selecting an already selected com.

**Comment by sprunk** [comment]
Sounds like an issue for more than 1 commander though. If you have N commanders, all selected, then invoking `selectcom focus` should focus one of them as well.

How about doing this around line 68 instead?
```diff
 local unitCount = #units

+-- if all comms are already selected, keep shifting focus among them
+if focusCamera and unitCount == 0 then
+ 	units = teamUnits
+ 	unitCount = #units
+end

 -- If no comms to select, nothing to do
 if unitCount < 1 then
 	return
 end
```

**Comment by K0NQUEROR** [comment]
Yeah makes sense for edge case I didn't consider. Updated

**Review by badosu — APPROVED** [review]

**Comment by badosu** [comment]
Thank you for the contribution, great job. Thank you @sprunk for the review and suggestion

**Review by sprunk — APPROVED** [review]

**Pull request merged**
