### PR TITLE
Fix: 87 wrecks to be blocking

### PR DESCRIPTION
**Pull request by Sipke82**
Fixes 87 corpses to be blocking.

### CODE REVIEW

**Comment by sprunk** [comment]
Keep in mind blocking corpses for sea units (ships and hovercraft) carries a tradeoff since you can't place floating buildings over a sunken blocking wreck, even if it's so deep it shouldn't matter.

**Comment by Sipke82** [comment]
Thanks, that is a good point. 
I did test that Ships can sail over them. and that subs are being blocked. Unless the wrecks are really deep, then the sub can travel over them.
So i guess its a nice feature that sometimes subs/torpedoes can be blocked by wrecks.
It would be nice if someone could fix for construction of floating buildings.

With regard to hovercraft wrecks, they are also deposited at land, which looks really weird when all kind of units go through those wrecks.

**Comment by Beherith** [comment]
Im not sold on this, especially with things like flea and peewee corpses, this will greatly alter mobility on the battlefield, and the UW bug is better non-blocking then.

**Comment by badosu** [comment]
Is there any issue present in current codebase that is or can be addressed by this PR?

**Comment by drivver44** [comment]
is there any reason to keep this PR public at this time 
it fails the checks and is over 2 years old

**Comment by WatchTheFort** [comment]
Do we even want wrecks to be blocking? One of the annoying things about Total Annihilation was wreck fields making pathing impossible.

**Comment by sprunk** [comment]
> annoying things

skill issue

**Comment by ipkh** [comment]
Big wrecks need to block.  I can see bots climbing over smaller ones.  It would be nice if Artillery didn't engage when blocked by wrecks.
Overall, the pathfinder can get really silly sometimes. I've seen units drop down hills trying to build on the edge and get stuck.

**Comment by drivver44** [comment]
heaps in general are not blocking plus their height is generally not a factor to gameplay

**Pull request closed without merging**
