### PR TITLE
xmas snow tree test

### PR DESCRIPTION
**Pull request by Beherith**
Please test and tune:

image

### CODE REVIEW

**Comment by saurtron** [comment]
Just 1/10th of features have lights, no? I think your photo has like 9/10 :D... probably more density there too.

Also, only trees? So conservative!

xmas

Looks great! (for the trees lol, the crystals is just playing with it) but default values as they are right now in the PR look a bit too low imo.

**Comment by saurtron** [comment]
btw, for a more dynamic xmas, ramping up the number of lights as xmas approaches:

(I guess there's a reason to not have too many lights, but just an idea)

```lua
local function getXmasFactor()
  local xmasFactor = 1
  local day = tonumber(os.date("%d"))
  local month = tonumber(os.date("%m"))
  local bracket = 4

  if month == 12 and day < 25 then
    xmasFactor = math.max(1, bracket - math.floor((25-day)/bracket))
  end
end
```

At gfx_deferred_rendering_GL4.lua -> `featureID%(math.floor(lightTable.fraction or 1)/getXmasFactor()) == 0`

At DeferredLightsGL4config.lua -> `count = count*getXmasFactor()`

**Comment by Ruwetuin** [comment]
image
note that tilted trees have get straight lights

**Comment by Beherith** [comment]
Tilted trees dont get it cause the effect is actually world-positioned, not unit positioned
@Ruwetuin you added 60 lights per tree, what does the final fraction end up as? Please make sure its less than 1/6th, as a lot of maps have thousands of trees and I ran into mild issues when spawning 100,000 lights at the same time.

**Comment by Beherith** [comment]
> Just 1/10th of features have lights, no? I think your photo has like 9/10 :D... probably more density there too.
> 
> Also, only trees? So conservative!
> 
> xmas
> 
> Looks great! (for the trees lol, the crystals is just playing with it) but default values as they are right now in the PR look a bit too low imo.

Yeah I adjusted down to 1/10th after the screenshot.

**Comment by Beherith** [comment]
@Ruwetuin @saurtron I see fraction peaks at 1/5th, perfect!

**Pull request merged**
