### PR TITLE
Addressing one way llt engagements

### PR DESCRIPTION
**Pull request by drivver44**
this is a test run to see how viable one of the aimposition rework standardization rulesets works assuming this has minor unknown consiquences that are not given to zecrus i would consider this a minor success if the change proves to be competantly good this change is to be kept however if the change is neutral or negative its to be reverted by may 15th 2024

### Work done
moved the midpositions of the llts to by aligned with the weapon mount 
changed
image

current
image

#### Addresses Issue(s)
if an llt is placed significantly below and near max range to another
the llt can and will kill the apposing llt
while said apposing llt cannot engage the other llt

### CODE REVIEW

**Comment by drivver44** [comment]
considering the full consiquences of the change
i do not want this pr merged unless im actually up and able to respond to any issues
its a bit more than anticipated

**Comment by Ruwetuin** [comment]
did the selection box also change due to unit radius midpoint being higher up?

**Comment by Beherith** [comment]
So the problem being solved is low ground range advantage?

**Comment by drivver44** [comment]
> did the selection box also change due to unit radius midpoint being higher up?

Yes on box selection as we use midposition for that 
On mouse over it shouldn’t be as the hitbox is used for mouse over selection

**Comment by drivver44** [comment]
> So the problem being solved is low ground range advantage?


That’s one of the problems
On certain maps there are spots where llt can fire at another llt and cannot be seen
There was one known case to me on dsdr 4.0 on the north center hill where such a case occured
Core llt did it best vs arm llt as the core llt is shorter than arms 
By about 7 Elmos 
I cannot emphasis enough that this is truely a test

Unfortunately with how old the relevant bug report replays are
I cannot bring them here as refference 
I would have to scour the discord for those replays 

I’ll lastly note that I don’t trust these changes to be overall better for the game

**Comment by drivver44** [comment]
Apologies I should clarify
The one way llt engagements that occur I can probably find some replays of that
The ones where an llt cannot be phically seen however I doubt I can easily find those in the next two days

**Comment by WatchTheFort** [comment]
@Zecrus2 Please have the balance team test and either merge or close

**Comment by KyleAnthonyShepherd** [comment]
Working on an engine PR that should allow this to be reverted if desired, so that units shooting at LLTs can fire at the base or middle instead of way up high at the turret. 

This PR was a nerf to Plasma Bots, due to the height of the aimpos, and the resulting reduction in plasma range, and makes their range ring inaccurate vs LLTs
image
This is the furthest a plasma bot can be and still fire at the arm LLT.

**Comment by drivver44** [comment]
Would be nice but one way engagements on like minded units need to be
tested for heavily

**Pull request merged**
