### PR TITLE
Commander movedeff and colvol changes

### PR DESCRIPTION
**Pull request by drivver44**
### Work done
addressed known issues of commanders on 2x2 movedeffs by forcing commanders to 4x4
see https://clips.twitch.tv/EnticingTastyParrotTF2John-1RHJwwfSwwodjQ8Y as an example
also addresses bad colvols to 48 60 48 which fully covers the model at this time 

#### left is branch right is current
image

### CODE REVIEW

**Comment by 6AKU66** [comment]
It's a problem with armada commander only, cortex commander is not affected by that problem with d-gun.

**Comment by Ruwetuin** [comment]
You must know that when we went from OTA model to BAR's version of the commanders I increased the model size like ~20% but only increased the colvol size like 5% so commanders could still dodge incomming shots/rockets well enough. The new suggested colvols would make this really hard!

**Comment by drivver44** [comment]
> You must know that when we went from OTA model to BAR's version of the commanders I increased the model size like ~20% but only increased the colvol size like 5% so commanders could still dodge incomming shots/rockets well enough. The new suggested colvols would make this really hard!

Scaling units without adjusting the colvol fully leads to bad cases such as balance of rocket bots being dependant on commander colvol. units that get scalled up or down should have their colvol following that. The current colvol doesnt even fit inside of the movedeff of the commander (being 4 units larger) 
the worst offender is not adjusting the movedeff size at all which is the really needed part. commanders dont need to be the size of a pawn on the spacing to be effective at their job. in fact the movedeff size increase is a general buff to the functionality of the commander. Better ensurances for larger firing arcs at close range are quite important.
that being said about colvols and movedeffs

the last thing to note is that the commander colvol height is incorrect by 8 units regardless

the other solutions to the commanders colvols are as follows which i think are the best overall
* add usepiececollision  and add a hitbox for the legs and body in a squared fashion
the width would be the same but the body would contain the aimposition.
this leads to the player having to care about the commander bodies facing and allows for odd micromanagement events to happen
* reduce the commander colvol to 40 wide but also change the movedeff size to 3x3
likely comes with some scalling down of the commander but also resolves the issue that i have with the commander being larger than its movedeff


Last thing to note
the colvol change is also to ensure that units will do their full intended damage as without the increase in size lasers get nerfed a bit vs commanders that shouldnt be occuring.

**Comment by sprunk** [comment]
> bad cases such as balance of rocket bots being dependant on commander colvol

This is a good case of balance. In fact BAR is proud of physically simulated projectiles so leveraging it is the best case of balance

> units that get scalled up or down should have their colvol following that

Colvols that get scalled up or down should have their model following that

> The current colvol doesnt even fit inside of the movedeff of the commander

Not a problem, they are separate traits for a reason

> the last thing to note is that the commander colvol height is incorrect by 8 units regardless

Colvol is correct. Model is incorrect by 8 units

> the other solutions to the commanders colvols:
> 1)
> 2)

3) keep as-is because it's done for a reason

**Pull request merged**
