### PR TITLE
Mine gridkeys

### PR DESCRIPTION
**Pull request by TheSilverHornet**
### Work done
Updated minelayer and decom gridkey layouts for better sanity/utility.

#### BEFORE:
image
image

#### AFTER:
image
image

### CODE REVIEW

**Comment by badosu** [comment]
I see many minelayers still have mines on utility instead of combat. armfast, armconsul, naval minelayers

**Comment by TheSilverHornet** [comment]
Consul has no space on combat for them, and twitcher should mirror that. Armfast has no mines, assuming you meant corfast?

Naval engies also have no space on combat, and it makes sense for them to mirror the consul & twitcher in mine layout.

Commando arguably should have them left on utility, but xx is a much nicer keypress when microing them

**Comment by WatchTheFort** [comment]
Mines make more sense under combat than they do under utility. Is there a way to standardize the menus so that mines are always under the combat tab?

**Comment by resopmok** [comment]
I would not merge this, as the proposed changes create inconsistencies for accessing mines depending on the constructor. For example, mines remain in the utility category for some units while moving to the combat category for others. This creates a situation where users need to memorize different hotkeys for the same build option, dependent on the unit they have selected. This goes against one of the core design choices around grid menu - keeping the same unit types in the same hotkey locations across all units.
While I agree that putting mines in the utility category is not ideal, as noted, there simply isn't room in the combat menu of some minelaying units to accommodate it. Thus, mines were put in the utility category, which isn't seen as a great hardship given the lesser frequency of in-game use than other combat menu options.
Lastly, this change will affect what users already have memorized as part of their hotkey setup. Given that grid keys is now default, any changes to the layout must be consistent and sensible enough to warrant forcing a significant chunk of the player base to relearn them. Please close this issue without merging.

**Comment by WatchTheFort** [comment]
Closing as per resopmok's comment

**Pull request closed without merging**
