### PR TITLE
Fix assignment of UNDERWATER category

### PR DESCRIPTION
**Pull request by kroIya**
Same fix as https://github.com/beyond-all-reason/Beyond-All-Reason/pull/3722 but for Base Builder turrets from the extra modoption.

### CODE REVIEW

**Comment by sprunk** [comment]
Could there be more (given these were missed after #3722)? Perhaps run a general check (via `unitdef.isImmobile and not unitdef.isBuilding`)

**Comment by sprunk** [comment]
> Great idea, although those unitdefs are not a thing and I'm not 100% sure what's responsible for a unit counting as a "building".
I ended up running if ud.minwaterdepth and not ud.yardmap and (not ud.speed or ud.speed == 0) then

Are you running it in unitdefs_post or somesuch? My line would have to run from a widget but would catch everything and do so reliably.

**Comment by Damgam** [comment]
corfrt couldn't be attacked by Flagship guns...

**Comment by Damgam** [comment]
Armada one works just fine.

**Pull request merged**
