### PR TITLE
T1 pop up ghost fix

### PR DESCRIPTION
**Pull request by KyleAnthonyShepherd**
Add yardmaps to T1 pop-up turrets, so ghosts and residual radar dots appear once they leave LOS, better mimicking T1 walls, making it a bit easier for players to target locations where they have seen a T1 pop-up turret.

### CODE REVIEW

**Comment by WatchTheFort** [comment]
Do the Scavenger popups also need this change?

**Comment by Beherith** [comment]
This is too far into balance territory for me to decide, @Zecrus2 please provide your thoughts.

Though as a player, I do indeed not enjoy popups not becoming ghosted, and trivially overridiing this with a widget to do this for me is more than possible, so I recommend merging.

**Comment by Beherith** [comment]
And the question is open, do scavdtf etc need this change too?

**Comment by KyleAnthonyShepherd** [comment]
Yes, It looks like corscavdtf, corscavdtl, and corscavdtm, need this change

**Comment by Beherith** [comment]
Ty!

**Pull request merged**
