### PR TITLE
Improved 3D models

### PR DESCRIPTION
**Pull request by Tharsy**
This change improves the models for the "armadvsol", "corhrk", "corwolv" and "cormart''

Armadv: The panel has been given a backface so it's no longer see-through from underneath. The dead model has been improved to have a different shape from the alive model.

Corhrk: Patched up many errors in the mesh and UV, remodelled and retextured some parts of the model.

Corwolv: Un-squashed the barrel and improved some UVs

Cormart: Full redesign to separate the unit top-down silhouette from the corwolv, added a unique animation for it to stand on its tracks when the unit is halted.

### CODE REVIEW

**Comment by Beherith** [comment]
Armadvsol:
Looks wonderful, excellent work. 

Corhrk:
Great chicken legs, needs an update to the buildpic and its footprint decals. 
Could you possibly split out the cormart into a different PR? 
Great wreck model too.
Collision volume on regular is screwed up, the dead one is fine (/debugcolvol)
image

Corwolv:
All round excellent, colvol seems off thoug:
image

Cormart:
This model is great, but I feel that its a tiny bit overkill for the current one. I would prefer this go into a separate PR. 
The script could absolutely use some fine tuning, as I think it lifts up too fast and too high. Would need constant acceleration liftup imo, to half this height. 
Colvol also needs to be redefined:
image

**Comment by 6AKU66** [comment]
What is purpose of adding animation for Cormart? Animation is not free and also that animation as i understand is changing gamebalance.

**Comment by drivver44** [comment]
@Zecrus2 this pr needs a review from you with the quacker model change

**Comment by Zecrus2** [comment]
The new quaker model is much more interesting than the old one, but it seems a bit large considering its cost: 
image
 I think the model better fits its cost when it is scaled by 0.9: 
image
 It is a bit strange that the animation is visual only with no changes to how the unit functions, but I can test out a how the unit balance would work with reduced turnrate and acceleration so it works better with the pack/unpack effect.  It might also be possible to script the unit to only fire when deployed, which could be interesting to look into but would be a much larger change to the unit.  All of this can be done after merge.

**Comment by 6AKU66** [comment]
Visual only? I was thinking it's can shoot only when it's deployed.

**Comment by TheSilverHornet** [comment]
> It is a bit strange that the animation is visual only with no changes to how the unit functions
not entirely true, the raising also raises the weapon origin, meaning it can potentially shoot over things.  It isn't a huge difference, and unless it allows it to shoot from right behind a T2 wall now, I would assume that being able to be a little closer to it without being blocked, not much of a real gameplay change.

Just checked something as sanity, and it has maxwaterdepth of 0, so there's no chance it could shoot from shallows it couldn't previously - but other the T2 vehicles (and even T1s) have maxdepths along the lines of 8, 12, etc, is there a reason this doesn't?  For some weird reason tiger has depth of 100 set (bull being 15).

**Comment by Tharsy** [comment]
> It is a bit strange that the animation is visual only with no changes to how the unit functions, but I can test out a how the unit balance would work with reduced turnrate and acceleration so it works better with the pack/unpack effect. It might also be possible to script the unit to only fire when deployed, which could be interesting to look into but would be a much larger change to the unit. All of this can be done after merge.

The quaker redesign at its core is supposed to only change the unit's profile so it is easily distinguished from it's t1 variant. similar to how the Mauser looks completely different to the t1 variant. I have kept the part count the same as the original model and any balance implications to a minimum. 
The current state of the game I have seen is that the quaker is more expensive yet slightly worse in most aspects to the mauser, so giving it an easier time shooting over obstacles or other units shouldn't give it much more of an advantage other than being able to sit closer to a t2 wall.
I think sizing the unit down to 0.9x is also a perfect change to better keep it a similar height to the mauser

**Comment by Beherith** [comment]
The new T2 artillery piece with its deploy animation should be moved to legion units. The other three are wonderful graphical updates to existing units.

**Pull request closed without merging**
