### PR TITLE
Carrier Spawning button

### PR DESCRIPTION
**Pull request by Xehrath**
Added a button for enabling/disabling spawning of drones.

### CODE REVIEW

**Comment by WatchTheFort** [comment]
Our goal should be minimizing the number of unique commands on the command palette. What is the point of a carrier that is not spawning drones?

**Comment by Zecrus2** [comment]
Each drone currently costs a small amount of resources (15m 500E) so turning a carrier off can make sense when you are trying to save up resources or when the carrier is trapped under enemy aa.

**Comment by WatchTheFort** [comment]
We should use the existing On/Off or Wait commands, rather than adding another unique command.

**Comment by sprunk** [comment]
> We should use the existing On/Off or Wait commands

Wait prevents movement and On/Off prevents having other onoffable features (radar etc).

**Pull request merged**
