### PR TITLE
Cleanup seismic display for units

### PR DESCRIPTION
**Pull request by StanczakDominik**
### Work done

- Hornet cleaned up these relevant units appearing on seismic detector

#### Test steps
- [x] Ensure the affected units (Hornet list them out plz this is a git showcase) show up or don't show up on seismic (to be filled out later)

### CODE REVIEW

**Comment by TheSilverHornet** [comment]
Units in question:

Umbra (armjam)
Compass (armmark)
Omen (corvrad)
Deceiver (corspec)

Note they need to be in an IDS range but not visible to the player, and also moving, to be detected in the previous state. The hill on Quicksilver is ideal for this, with the Nemesis on low ground.

**Comment by StanczakDominik** [comment]
# With this change applied
screen_2024-03-02_19-33-56-689

screen_2024-03-02_19-34-17-006

# Without this change applied, same setup
screen_2024-03-02_19-36-45-756

**Comment by thehobojoe** [comment]
The title of this PR does not match what it does, this is not just a cleanup but a big balance change. Was this a GDT item?

**Comment by TheSilverHornet** [comment]
> The title of this PR does not match what it does, this is not just a cleanup but a big balance change. Was this a GDT item?

They weren't intended to act this way, and almost never appears in a game, less still in a relevant fashion.  It has been discussed with GDT yes, verdict being 
image


( https://discord.com/channels/549281623154229250/1212989184621674516/1213032227387220038 )

**Pull request merged**
