### PR TITLE
fix(unitdefs): remove no-op commands from static air repair pads

### PR DESCRIPTION
**Pull request by salinecitrine**
Previously, static air repair pads had a significant amount of commands shown - fire-at-will, guard, fight, for example. None of these commands had any real effect, though commands would show as queued. In addition, this allowed these buildings to have a queued selfd command, which would never be executed, yet confused the gui_selfd_icons widget.

This commit sets all static air repair pads to builder=false, and onoffable=false, which has the effect of removing all commands.

#### Test steps
1. Select a static air repair pad.
2. It should have no commands available.
3. It should not be able to receive any orders such as fight or patrol (and should not display them as queued commands)
4. It should still be able to selfd.
5. Aircraft should still be able to land and be repaired as normal.

#### BEFORE:
*note: this includes the "Share Unit" command from the factory share command widget. This command is also a no-op.*
before

#### AFTER:
after2

### CODE REVIEW

**Comment by Beherith** [comment]
Does on/off have an effect within the gadget?

**Comment by salinecitrine** [comment]
> Does on/off have an effect within the gadget?

That's an excellent point. It appears that they work identically regardless of if they are toggled on or off. I suppose I'll figure out how to remove that button too.

**Comment by salinecitrine** [comment]
> > Does on/off have an effect within the gadget?
> 
> That's an excellent point. It appears that they work identically regardless of if they are toggled on or off. I suppose I'll figure out how to remove that button too.

Done

**Review by thehobojoe — CHANGES_REQUESTED** [review]
None of these values need to be set to false, these changes work as described by simply removing the `builder` and `onoffable` values.

**Comment by salinecitrine** [comment]
> None of these values need to be set to false, these changes work as described by simply removing the `builder` and `onoffable` values.

Done!

**Review by thehobojoe — APPROVED** [review]

**Pull request merged**
