### PR TITLE
Mass hitbox standardization

### PR DESCRIPTION
**Pull request by drivver44**
the goal of this pr is to bring as many units as feaseable into a single hitbox standard
this follows on the hitbox proposal i have made to the gdt about a year ago

the overall scheme is to follow the model makers intentions with hitboxes for the unit
no longer are units allowed to fire through themselves when in masssed groups
units such as missile trucks now have to aim for an open area instead of firing through their neighboring turrets

most of the units that are in this pr are vehicles but there are some bots
performance was a factor for units such as the scout rovers that vehicles have

in regards to the pr meantioned in the comments here https://github.com/beyond-all-reason/spring/pull/891
that has been merged and this pr works fully as expected

two units have changes listed but have no change in game but do have a change listed
* armfido
* corlevl
these units have real issues on tight nit hitboxes
the armfido has a unit script issue that has mostly gone unnoticed
the corlevl has unknown level of issue
as such 
both of these units have a hitbox defined in collisionvolumes.lua which are off until said issues get resolved

### CODE REVIEW

**Comment by KyleAnthonyShepherd** [comment]
image
I got a lot of friendly fire when testing the 2-part hitbox for correap

**Comment by KyleAnthonyShepherd** [comment]
*wacky waving inflatable tube man gif*
So, it turns out cannon shots are not properly using pieceCollisionVolume.
The friendly fire check for cannons is still using collisionvolumescales in the unitdef.

**Comment by KyleAnthonyShepherd** [comment]
Until this PR or something like it gets merged into the engine, I do not recommend cannon units using multiple collision volumes, as there is no way to set the friendly fire checks to be accurate to the multiple collision volumes.
https://github.com/beyond-all-reason/spring/pull/891

**Comment by drivver44** [comment]
this PR is to be merged when the next engine release occurs

**Comment by Ruwetuin** [comment]
@drivver44 is this still relevant?

**Comment by drivver44** [comment]
> @drivver44 is this still relevant?

yes its just that the gdt has not resolved what hitboxes are meant to be for so long
this was originally started when instigator changes were seen as a positive change

**Comment by drivver44** [comment]
the pr in question from the engine side has already been merged 
and became a feature in the qtpfs engine release that occured in august or September of 2023
the gdt still has not resolved what hitboxes are meant to be
until they do so this pr is relevant

**Pull request merged**
