### PR TITLE
fix(SmartSelect): No selection with ctrl pressed

### PR DESCRIPTION
**Pull request by badosu**
Check if engine has just deselected via mouserelease on selectbox and
preserve smartselect state.

Correct fix is to unhardcode engine selection modifiers.

Ideal fixes are:
  - rework mousepress and mouserelease ownership logic
  (unfeasible due to retrocompatibility concerns).
  - provide a BoxSelection callin that, together with
  `Spring.SetBoxSelectionByEngine`, provides the necessary tools to
  perform this role without the current hacky implementation.

Also:

- Simplify minimap selection
- Return early on invalid selectbox
- Remove noop parameter on special MousePress from widget manager

Second commit leverages the ability to inspect for valid selectbox coordinates and 'guessing' when engine selectbox was just released to optimize and simplify a lot of stuff.

Fixes https://github.com/beyond-all-reason/Beyond-All-Reason/issues/1536 https://github.com/beyond-all-reason/Beyond-All-Reason/issues/1470

### CODE REVIEW

**Comment by badosu** [comment]
Would appreciate if the reviewer could test it to be sure I didn't miss anything weird, thanks!

**Comment by Ruwetuin** [comment]
tested it, hold CTRL and select 1 unit = this results in errors due to following use:

function widget:SelectionChanged(sel)
	selectedUnits = sel
	selectedUnitsCount = Spring.GetSelectedUnitsCount()
end

where selectedUnitsCount will be 1 and selectedUnits contains no units

**Comment by Ruwetuin** [comment]
also be aware that the widgethandler contains this:


function widgetHandler:SelectionChanged(selectedUnits, subselection)
	for _, w in ipairs(self.SelectionChangedList) do
		if widgetHandler.WG.smartselect and not widgetHandler.WG.smartselect.updateSelection then
			return
		end
		local unitArray = w:SelectionChanged(selectedUnits, subselection)
		if unitArray then
			Spring.SelectUnitArray(unitArray)
			return true
		end
	end
	return false
end

**Comment by badosu** [comment]
Hmm, how can I reproduce?

**Comment by badosu** [comment]
Thanks for testing! I think I know how to address this.

**Comment by badosu** [comment]
@Ruwetuin  Fixed, this should address this issue. Keep in mind there is a con with current implementation whereas holding ctrl and selecting no units won't cancel the current selection, this is due to inability to distinguish between engine deselect and user selecting empty with ctrl held. This should be revisited when modifier is unhardcoded.

**Comment by badosu** [comment]
I've played a few games, no issues so far

**Pull request merged**
