### PR TITLE
Thugs and maces adopt social distancing

### PR DESCRIPTION
**Pull request by TheSilverHornet**
Not enough room to swing a plasma cannon.  As discussed in GDT thread.

Before:
image

After:
image

### CODE REVIEW

**Comment by PtaQQ** [comment]
Approved by the GDT tentatively, to be checked soon if it creates any side issues.

**Comment by marcushutchings** [comment]
This may not be ideal. By changing the step size of the units you impact the gaps they can walk through. In other words. they are more likely to get trapped in bases when it looks like they should be able to get through. Drivver put a lot of work in trying to match up the movetypes with units collision radius. I'd advise against the approach taken here, and instead suggest that you raise an engine ticket requesting the ability to configure the distance that units will try to stand apart - referencing this PR as an excellent example of the desired result.

**Comment by sprunk** [comment]
It's not just about standing apart but also not coming too close during movement (since units should be moving most of the time anyway and they need to maintain freedom of gun movement regardless). In particular this means not coming too close to buildings.

**Comment by marcushutchings** [comment]
I was implying the maintaining of distance while moving, but thank you for the clarification so that it is crystal clear for everyone reading this.

Maintaining a distance from buildings for this purpose is fine as a long as it is a soft-enforcement. The movement system is particulrly strict and prevents units intersecting a building's are at all. So increasing the unit's step size also increases the strict enforcement of where a unit can move in relation to buildings.

To be more correct, for aiming the issue is the building's collision volume, not the yardmap. The unit's step size impacts interaction with the yardmap (every building *effectively* (and I say effectively here for the purposes of understanding rather than 100% accuracy) has one, even if it an implied "I fill all these squares") - the importance of keeping away from buildings is to leep away from the collision volume - not the yardmap.

This is why I suggest I implement a feature in-engine to allow devs to achieve unit spacing.

**Comment by marcushutchings** [comment]
Are we talking in the right place? I've noticed this has been merged anyway.

**Comment by Jazcash** [comment]
> Are we talking in the right place? I've noticed this has been merged anyway.

[There](https://discord.com/channels/549281623154229250/1132599985247113226) [are](https://discord.com/channels/549281623154229250/1201511017369305140) [several](https://discord.com/channels/549281623154229250/1183501397203882004) [threads](https://discord.com/channels/549281623154229250/1209156299787472916) related to this stuff in the GDT forum, I think the last one is the one specific to this PR.

GDT agreed to merge this PR as a kind of live trial test to see how we feel about this way of solving the problem.

**Pull request merged**
