### PR TITLE
Update Lua JSON parser to version 0.9.50

### PR DESCRIPTION
**Pull request by lazau**
### Work done
Updated common/luaUtilities/json.lua from 0.9.20 -> 0.9.50. Note that the library also has a [1.0.0 version](https://github.com/craigmj/json4lua/blob/master/json/json.lua) which does not contain [decode performance optimizations of 0.9.50](https://github.com/luaforge/json/blob/f289058bfbbf51a5f5d55acb82c3137b2eb3525a/trunk/json/json.lua#L21).

The code is copied from [luaforge/trunk/json/json.lua](https://github.com/luaforge/json/blob/master/trunk/json/json.lua) with the diffs in [json.lua.patch.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/13620696/json.lua.patch.txt) applied. Additional changes in the patch includes
- Drop `require` calls as the spring lua evaluator prohibits them but instead exposes them as globals. [LuaParser](https://github.com/beyond-all-reason/spring/blob/99d6732ceb69f2ea7665e35ba7ca254426a82602/rts/Lua/LuaParser.cpp#L137)
- Wrap `decode` call around an `instrumentedDecode` function which create a tracy zone when tracy is enabled (no-op in release builds).
- Module returns a table containing the expected interface `json.encode` `json.decode` `json.null`.

#### Test steps
- [ ] In local Beyond-All-Reason.sdd game, replace common/luaUtilities/json.lua with the new version.
- [ ] Launch any map using the updated game. Sample command line `./spring --isolation --write-dir '$BAR_DIR/' ./bar_debug_launcher_script.txt` With [bar_debug_launcher_script.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/13620665/bar_debug_launcher_script.txt) (replace `$CUSTOM_GAMETYPE_NAME` with the name in Beyond-All-Reason.sdd/modinfo.lua). 

### Performance Improvements
Speeds up default load times by about ~1 sec on Linux and ~1.3 sec on Windows.

#### Linux

linux_json_0_9_20
linux_json_0_9_50

#### Windows

win_json_0_9_20
win_json_0_9_50

### CODE REVIEW

**Comment by Beherith** [comment]
This is very interesting, i did not expect us to be doing that much json load work, where is all this json loaded i18n?

**Comment by Beherith** [comment]
Lazau, are you in our discord? :)

**Comment by Beherith** [comment]
I tested it, seems to work absolutely fine, and the load speed is indeed faster!

**Comment by StanczakDominik** [comment]
This may have caused issues with loading single player scenarios, or at least I have no better idea for why this bug has now popped up: https://discord.com/channels/549281623154229250/1183204763605684254

```
[t=00:00:32.674766][f=-000001] Error: Failed to load: unit_scenario_script.lua  ([string "common/luaUtilities/json.lua"]:365: Unexpected character at Line 1 character 5576: ] (93) when reading array ({ or [ or ' or " or number or boolean or null expected)
Context: 
adstart008","featureloadout":[],"disablefactionpicker":true,"
                              ^)
```

**Comment by salinecitrine** [comment]
> This may have caused issues with loading single player scenarios, or at least I have no better idea for why this bug has now popped up: https://discord.com/channels/549281623154229250/1183204763605684254

I also encountered this error while developing a widget; it occurs when reading an empty array.

**Comment by Beherith** [comment]
Reverted this for the moment, as it does not like to parse empty arrays, and revert ensures scenarios still work :(

**Pull request merged**
