### PR TITLE
feat(cmd_blueprint): add blueprint widget

### PR DESCRIPTION
**Pull request by salinecitrine**
blueprint2

This widget allows players to copy units into a blueprint, and place any saved blueprints. The functionality is kept as close to default build mechanics as possible; line/grid/box/etc build work, for example.

The code is split into two widgets:

* `api_blueprint.lua`: handles build positions, drawing buildings, and provides some other utility functions.
* `cmd_blueprint.lua`: handles user interaction, UI, saving blueprints to disk, and tells `api_blueprint.lua` when to draw which blueprints.

It adds several bindable commands/actions, with these default hotkeys:
```
bind           Alt+sc_b  blueprint_place
bind           Alt+sc_c  blueprint_create
bind     Alt+Shift+sc_c  blueprint_create_selectionorder
bind           Alt+sc_d  blueprint_delete
bind           Alt+sc_[  blueprint_prev
bind           Alt+sc_]  blueprint_next
```

The standard rotation and spacing hotkeys apply to blueprints when the command for placing blueprints is active. When holding alt, the mouse wheel will also trigger `blueprint_prev` and `blueprint_next`.

#### Open questions

* What's the best way to handle build order within a blueprint? Currently, when creating a blueprint, you can choose selection order, or spatial sorting during placement.
* What kind of (simple) UI should go with this iteration of the widget? Right now it uses unit commands and hotkeys for creating blueprints, but a separate UI might be better.

#### Test steps
- Automated tests
  - [ ] test_cmd_blueprint_single.lua
  - [ ] test_cmd_blueprint_line.lua
- General graphics expectations
  - [ ] Displayed previews (while the "Place Blueprint" command is active) should follow the cursor without noticeable lag, including when placing large line/grid/etc formations
  - [ ] At no point should preview blueprints show when the "Place Blueprint" command is not active
  - [ ] Building outlines (red/yellow/green squares) should correctly indicate if: a building cannot be placed there (red), there is no constructor that can build that building (yellow), or that it is a valid placement (green)
- Creating blueprints
  - Unordered
    - [ ] Select any units, and choose "Save BP"
    - [ ] Confirm that the new units are available as a new blueprint through "Place Blueprint" on a constructor
    - [ ] Confirm that the units in a single blueprint are placed in spatial order (z ascending, then x ascending)
    - [ ] Confirm that the units in a line of blueprints are placed in spatial order (direction of line)
  - Ordered
    - [ ] Select any units, in a specific order, and choose "Save Ordered BP"
    - [ ] Confirm that the new units are available as a new blueprint through "Place Blueprint" on a constructor
    - [ ] Confirm that the units in a single blueprint are placed in the same order as they were originally selected
    - [ ] Confirm that the units in a line of blueprints are placed in the same order as they were originally selected (one blueprint at a time)
- Placing line/grid/etc formations of blueprints
  - Line
    - [ ] Have at least one saved blueprint, and select "Place Blueprint" on a constructor
    - [ ] Hold shift, place and drag a blueprint. Confirm that it previews and issues orders for the appropriate number and orientation of blueprints (a line directly between drag start/stop)
  - Snap Line
    - [ ] Have at least one saved blueprint, and select "Place Blueprint" on a constructor
    - [ ] Hold shift+ctrl, place and drag a blueprint (without hovering an existing unit). Confirm that it previews and issues orders for the appropriate number and orientation of blueprints (a line between drag start/stop, snapped to 90degree angles)
  - Grid
    - [ ] Have at least one saved blueprint, and select "Place Blueprint" on a constructor
    - [ ] Hold shift+alt, place and drag a blueprint. Confirm that it previews and issues orders for the appropriate number and orientation of blueprints (a filled grid between drag start/stop)
  - Box
    - [ ] Have at least one saved blueprint, and select "Place Blueprint" on a constructor
    - [ ] Hold shift+ctrl+alt, place and drag a blueprint. Confirm that it previews and issues orders for the appropriate number and orientation of blueprints (the border of a grid between drag start/stop)
  - Around
    - [ ] Have at least one saved blueprint, and select "Place Blueprint" on a constructor
    - [ ] Hold shift+ctrl, and hover an existing unit. Confirm that it previews and issues orders for the appropriate number and orientation of blueprints (a circle around the hovered unit)
- Manipulating blueprints
  - Rotation
    - [ ] Have at least one saved blueprint, and select "Place Blueprint" on a constructor
    - [ ] Using the standard rotation controls ([/]), change the rotation
    - [ ] Confirm that the blueprint rotates in the expected direction (including the component buildings), and when placed, places with the correct orientation
  - Spacing
    - [ ] Have at least one saved blueprint, and select "Place Blueprint" on a constructor
    - [ ] Using the standard spacing controls (shift+alt+z/x), change the spacing. It can be positive or negative
    - [ ] For each formation, confirm that it respects the chosen spacing for the selected blueprint, both in preview and placement
- Navigating and deleting blueprints
  - Hotkeys
    - [ ] Create 2 or more blueprints
    - [ ] Select "Place Blueprint" on a constructor
    - [ ] Confirm that the hotkeys for next, previous, and delete are displayed (and match the hotkey configuration if it's custom)
    - [ ] Confirm that next and previous progress through the list of blueprints in the expected order
    - [ ] Confirm that delete removes the selected blueprint, and leaves the expected blueprint selected
    - [ ] Confirm that deleting the last blueprint shows that there are no blueprints selected
  - Mouse wheel
    - [ ] Create 2 or more blueprints
    - [ ] Select "Place Blueprint" on a constructor
    - [ ] Confirm that holding alt and scrolling the mouse wheel progresses through the list of blueprints in the expected order
- Saving and loading blueprints
  - [ ] Create 1 or more blueprints
  - [ ] Confirm that unloading and reloading the "Blueprint" widget correctly restores the saved blueprints, and that the first blueprint is selected afterward

### CODE REVIEW

**Comment by SethDGamre** [comment]
is this something that can be installed by conventional widget installation methods or do I have to use your branch?

**Comment by salinecitrine** [comment]
> is this something that can be installed by conventional widget installation methods or do I have to use your branch?

This is only practically usable by checking out the branch.

**Comment by WatchTheFort** [comment]
> What's the best way to handle build order within a blueprint? Currently, when creating a blueprint, you can choose selection order, or spatial sorting during placement.

Selection order, this shouldn't even be choice. This allows full player control over construction.

**Comment by sprunk** [comment]
what about symmetrical buildprints like the one on the screenshot? spatial sorting is great there

**Comment by WatchTheFort** [comment]
Bug: Spacing adjustment can go below zero, causing the entire placement preview to disappear.

For one blueprint (1× Dragon's Eye + 1× Dragon's Teeth) I could get the spacing back above zero with Alt+Z, for another blueprint (LLT surrounded by Dragon's Teeth) I could not get it back, no matter what I tried.

**Comment by salinecitrine** [comment]
rebased, removed unordered blueprint command, added sounds for some actions

**Comment by DeadlyPants253** [comment]
🎉

**Pull request merged**
