### PR TITLE
commented out set-signal-mask=0, so turret close script can be stoppe…

### PR DESCRIPTION
**Pull request by KyleAnthonyShepherd**
…d and interrupted by aiming function

### CODE REVIEW

**Comment by WatchTheFort** [comment]
Doesn't the function still need a signal mask, so other functions can interrupt it?

**Comment by KyleAnthonyShepherd** [comment]
I used the bos2cob.py script to compile the new .bos changes to cob

**Comment by KyleAnthonyShepherd** [comment]
It inherits the mask of the function that called it, so in this case it has a mask of 1

**Comment by Beherith** [comment]
Bos2cob outputs identical code to scriptor iirc, the optimizer is only useful for very complex animations. Thank you!

**Pull request merged**
