### PR TITLE
Options: Not build with right click with commander

### PR DESCRIPTION
**Pull request by badosu**
Commanders are arguably the most important unit in the game, they
shouldn't have a cumbersome default behavior affecting micro for the tradeoff
of an easy click to build mexes facility.

### CODE REVIEW

**Comment by badosu** [comment]
Yeah, I actually started the work with the option in mind but I gave up on the verbosity and specificity of it. If others think this should be an option I can do it.

**Comment by badosu** [comment]
Changed it to be an option

**Comment by badosu** [comment]
It is already an option, however it seems there's no interest in merging this PR. I'll give it a couple of weeks and then close

**Comment by badosu** [comment]
Closed due to lack of interest

**Comment by Beherith** [comment]
After going through and reading the code, and the discussion (sorry I have not done this sooner), I now understand why this is a useful, especially as an option. If the branch is deleted, is there no way to reopen? I would like to merge this.

**Comment by Beherith** [comment]
After testing, I see that toggling the option off does not prevent the commander building on a mex right click, the only effect is to not show the ghosted building when hovering over a mex with the comm selected. The commander still goes and builds a mex on a mex spot on both states of the option.

**Comment by simeonpfeiffer** [comment]
Building mexes/geothermal is done by intercepting the move and guard commands. The behaviour can be deactivated by disabling the plugins "RClick Quick Build".

**Comment by badosu** [comment]
@Beherith I'll test and get back to this. Maybe something changed

**Comment by badosu** [comment]
@Beherith Done, thanks for testing!

**Comment by Beherith** [comment]
Ty, ill try to test this tonight :) remindme otherwise

**Comment by sprunk** [comment]
?

**Pull request closed without merging**
