### PR TITLE
part 1of armbuilding hitboxes

### PR DESCRIPTION
**Pull request by drivver44**
the list of changed buildings 
armsilo armjuno armmercury armamphibgantryt3 armtidal armmoho  armafus

### CODE REVIEW

**Comment by drivver44** [comment]
@Zecrus2

**Comment by drivver44** [comment]
do not merge i forgot about offsets of hitboxes

**Comment by drivver44** [comment]
updated
fixed offsets for 
armafus
armuwadves
armamd

**Comment by Beherith** [comment]
Thanks, do tell when this needs a review!

**Comment by drivver44** [comment]
theres a few more issues i missed ill get this done in a few hours hopefully

**Comment by drivver44** [comment]
so list in total of changes
arm nuke defense (armamd)
armjuno
armmercury 
arm nuke silo (armsilo)
arm emp silo (armemp)
armafus
arm moho (armamex)
arm tidal (armtide)
arm t3 factories (armshltx and armshltxuw
arm t2 energy storage (both UW and regular version are mixed together as armuwadves
arm twilight mex (armamex)

should be safe to merge

**Comment by KyleAnthonyShepherd** [comment]
New hitboxes on left, old hitboxes on right.
Those are much more sane hitboxes

image
image
image
image
image
image

**Comment by drivver44** [comment]
my only concerns are on the t3 factories

**Review by Zecrus2 — APPROVED** [review]

**Pull request merged**
