### PR TITLE
Revise the ZH localization

### PR DESCRIPTION
**Pull request by WheatleyRed**
### Overview:
I have revise the ZH localization roughly.
First I revise the file content have the same sorting of EN origin file content. Because I find the ZH file has a Chaotic sorting and lose many content. Then translate the still EN content.
But interface file has many content to fix, and I need time to check the content which has been translated before. 
Also, I need to investigate what localization CN player like. For example, the raptor has translated to "shrimp", but I think it mean a type of dragon or the bird of prey. But maybe CN player already love the "shrimp".

### BUG/Error:
(1)buildMenu can't be translated. Once it translated, the buildMenu will disappear after the game start a late. I think it is depend on string compare, when the script not find the string, execution error.
(2)tips files invalid to translated. I have try FR too, the same.

### Suggestion:
MainMenu interface, more localization interface.

### CODE REVIEW

**Comment by WheatleyRed** [comment]
Press wrong button, sry

**Comment by WatchTheFort** [comment]
This is a fantastic effort, however rather than committing translations directly, we use the Transifex collaborative translation service.

Don't fear! Your work is not lost, you can upload the translated JSON files to Transifex, where the translations can be reviewed and approved.

[Check out the translator instructions on the Discord for how to join our Transifex project](https://discord.com/channels/549281623154229250/1066060678860914780/1066060678860914780)

[Chat with the other translators in the Chinese translation discussion thread](https://discord.com/channels/549281623154229250/991351714793918515)

**Comment by yajiedesign** [comment]
@WheatleyRed  Simplified Chinese has been translated in Transifex, but it has not been automatically merged. Is it because it has not been reviewed?

**Comment by WatchTheFort** [comment]
> @WheatleyRed Simplified Chinese has been translated in Transifex, but it has not been automatically merged. Is it because it has not been reviewed?

There is an issue with merging the translations to Github, but hopefully we will have it resolved soon.

https://community.transifex.com/t/transifex-integration-bot-is-immediately-closing-its-unmerged-pull-requests/4034

https://github.com/beyond-all-reason/Beyond-All-Reason/pull/3810

**Pull request closed without merging**
