### PR TITLE
Added 'Area control' and 'Anti-swarm' to T1 units descriptions

### PR DESCRIPTION
**Pull request by StanczakDominik**
This changes a few of the descriptions for T1 units, intended to steer newbies away from defaulting to them when they're more "precision" tools for particular applications rather than good all-rounders.

I added mention of "Anti-Swarm" (precendented by the Cortex Twin Guard) to:

- Centurions, whose "Medium Infantry Bot" description really conveys no useful information and makes people default to them when they should be using Maces in the first place. I considered `Anti-Swarm Area Control Bot` and "Anti-Swarm Mobile Laser Turret", these may be better ideas.
    - I am aware that you can also use these to solo a commander, but a short description like that will never convey the full scope of a unit anyway. I decided to ignore this.
- Razorbacks, for which the recent engine changes have really helped solidify their role as this.
- Pounders. I see them made by newbies quite often where basic medium tanks would do much better.
    - I originally intended to keep them as a `Anti-Swarm Riot Tank` because they don't have a laser weapon.

I also added an "Area ~~Control~~ Denial" tag for the T1 Heavy Laser Tower and Plasma Artillery. This is meant to convey that you aren't supposed to use these as defensive tools (for which they're inefficient), but to deny an area from afar, force the enemy to attack you or switch strategies. I welcome better ideas for a description for that.

This is a very first pass, I would like to do more broad changes in the future, but this change is self-contained and a good start.

### CODE REVIEW

**Comment by StanczakDominik** [comment]
How about "Area Denial", then?

**Comment by sprunk** [comment]
"Area denial" still sounds like denying the enemy from coming into the area around the tower. In general I think you'd have to put some explicit description like "offensive emplacement for shelling enemy front and not defending" to prevent people from assuming it's a defensive turret (but don't use this description, it's bad for other reasons). Perhaps people will assume it's a turret that regardless though and only learn via experience so perhaps the wording is unimportant and area control/denial works good enough, idk.

**Comment by sprunk** [comment]
`Siege artillery - not for defense`? It's a bit blunt and tautological but perhaps that's required to convey the point. I am not competent to talk about HLT.

**Comment by StanczakDominik** [comment]
It's a bit janky, like a "wet paint, do not touch" sign, but it would do the job 😁 I'm not trying to find perfect descriptions here, just steer people away from using these.

The HLT, as I understand it, is basically the same thing, but it's used to break rocket bot/beamer stalemates and can in return be broken by a transition to T1 vehicles, where mobile artillery outranges it. The T1 plasma artillery outranges everything on T1, so it forces an attack or teching, instead.

**Comment by WatchTheFort** [comment]
I think the more pertinent question is why is there a defence turret that's not for defence?

**Comment by StanczakDominik** [comment]
Note that all of these live in `units/CorBuildings/LandDefenceOffence/`, implying these are turrets, yes, but nobody says you have to use them for defense only!

In the grid menu they're under `Combat`, too, not `Defense`.

And then there's also [this fella](https://www.beyondallreason.info/unit/armvulc) 😜

**Comment by drivver44** [comment]
this pr as is 
is safe to merge

**Pull request merged**
