### PR TITLE
added unit deffs names to relevant move deff types

### PR DESCRIPTION
**Pull request by drivver44**
added unit deffs names to relevant move deff types
there is no functiuonality loss with this PR 
it simply allows for better organization of the movedeffs file

### CODE REVIEW

**Comment by sprunk** [comment]
any ways to entire this won't immediately get outdated as soon as somebody touches a unit def file?

**Comment by WatchTheFort** [comment]
This is fragile, as the comments must be kept up to date with code changes. If we need this formally documented, better to put a switch in the code that prints out all the unit names and their movement classes.

**Comment by drivver44** [comment]
the fragility is known 
yes i would like to have a file that specifically would be a master has everything for each class of thing
this is really for keeping things organized until movedeffs get better condensed into fewer amounts.
there is more working coming here that will be coming but its irrelevant to atleast having something here

this is a temp solution to a bigger issue

**Comment by drivver44** [comment]
if anything 
there is atleast documentation of what is used by what as of today
if the documentation breaks, its not happening anytime soon unless someone goes through and redos the unitdeff names

**Pull request merged**
