### PR TITLE
fix(cormexp.bos): Activation conflated with firing

### PR DESCRIPTION
**Pull request by badosu**
This has implications to balance as now the cormexp will keep mining while shooting.

If someone else has a fix that preserves previous behavior they are welcome, otherwise I'll just do this and call it a day (honestly I never figured out why it would make sense to not mine while firing, this keeps it consistent with corexp).

cc @Beherith

### CODE REVIEW

**Comment by badosu** [comment]
cc @KyleAnthonyShepherd

**Comment by KyleAnthonyShepherd** [comment]
Yup, in talking with other people, the consensus is to make it consistent with corexp, and keep extracting while firing. 

My fix will also wrap in a couple of other changes, such as removing the script-based reload time, and just using a unitdef burst weapon.

**Comment by WatchTheFort** [comment]
Why does this pull request include changes for bos2cob and related files?

**Comment by badosu** [comment]
it moves it out of Chicken folder

**Comment by badosu** [comment]
It's the only bos2cob util that is cross platform, and not particular to chickens

**Comment by badosu** [comment]
Ok, I'm closing this as soon as you send your PR @KyleAnthonyShepherd

**Comment by badosu** [comment]
Hmm.. maybe nobody interested in fixing cormexp?

**Comment by KyleAnthonyShepherd** [comment]
Almost ready to make the PR.
Turns out, there were a lot of little animation bugs, and weird ARMORED states, I'm trying to fix all at once

**Comment by badosu** [comment]
Ok since it seems the priority will be given to the new PR instead of addressing this for players ASAP I'm closing this

**Pull request closed without merging**
