### PR TITLE
CEG auto reloader

### PR DESCRIPTION
**Pull request by Beherith**
Enabling this widget will continously scan the effects/ folder for changes.
If any cegs are changed, it will try to validate their syntax.
If syntax correct, all cegs are reloaded.
The last CEG to be modified is spammed every second at the cursor.

PR contains fixes to the syntax of a few effects.

### CODE REVIEW

**Comment by Beherith** [comment]
@Protar1458

**Comment by icexuick** [comment]
I get this: 

```
[t=11:22:24.558123][f=0001859] Loading:  LuaUI/Widgets/dbg_ceg_auto_reloader.lua
[t=11:22:24.561641][f=0001859] Error in Initialize(): [LuaVFS::Include(synced=false)][pcall] file=gamedata/resources.lua error=2 ([string "gamedata/resources.lua"]:115: table index is nil) ptop=1 cenv=false vfsmode=rMmeb
[t=11:22:24.561686][f=0001859] Removed widget: CEG Auto Reloader
```

**Comment by icexuick** [comment]
Error got resolved by removing a custom folder I had in my BAR/data/bitmaps folder.
Afaik, not a default folder - probably some old testing by me.
But with this gone, the CEG autoloader works nicely.

Removing the echo of spawncegs would be a little more ideal, so it doesnt spam the console-log which can hold useful info on broken/bad cegs.

**Comment by WatchTheFort** [comment]
Is this ready to be merged? Should it be split into two PRs, one for the auto reloader widget and one for the CEG fixes?

**Review by icexuick — COMMENTED** [review]
All good!

**Pull request merged**
