### PR TITLE
Standardization of Legion Unit Icons

### PR DESCRIPTION
**Pull request by ThanosDeGraf**
### Work done

Changed the icons for:
- Arquebus and Lance by rotating the railgun emblem 45° (now with much less negative space) 
- Karkinos (Now shares the same Riot Gun emblem as the Pounder, with a Laser background, reflecting its dual armament)
- Ballista and Cerberus (The upsized T1.5 rocket and raid units now has a single box, emphazising its increased power without being confused for their smaller cousins)
- Proteus and Infestor (They are getting completely new Icons, woho!)

#### BEFORE:
allterrain_t2_rail(1)legkark(1)vehicle_t1_tank_rail(1)

kbot_rocketkbot_t2_raid
(Ballista was using the T1 Rocketbot icon, while the Centaur had the T2 Raid Icon. They were not changed but replaced by the following new design)

#### AFTER:
legkarkbot_t15_rocketbot_t15_raid

KarkinosBallistaCentaur

allterrain_t2_railleginfestorlegceb

ArquebusInfestorProteaus

vehicle_t1_tank_rail
(forgot to make a lance screenshot x.x)

### CODE REVIEW

**Comment by ThanosDeGraf** [comment]
If there are more units currently WiP or i missed an icon that could use a looking at, I'd like to do it in this request.

**Comment by icexuick** [comment]
I think this is a good update.
@Ruwetuin can you check the branch conflict?

**Comment by icexuick** [comment]
I updated the icons + increased size on legceb a tad.
And created the inverted icons.
Should be ready now.

@Ruwetuin can you check the conflicting stuff?

**Comment by Ruwetuin** [comment]
@Damgam all yours!

**Pull request merged**
