### PR TITLE
test_runner: add test suites

### PR DESCRIPTION
**Pull request by keelefi**
Currently, to test a widget you have to create a new file for each test. However, each new file requires it's own set of initialization routines, i.e. skip(), setup() and cleanup(). This is suboptimal when multiple tests would like to share a common implementation of these routines.

To allow DRY, support test files having several tests. The initialization and teardown is run for each test separately even though the implementation is shared.

Test functions are discovered by their names, i.e. test functions are all the functions that start with `test`.

#### Test steps
- Open Skirmish with "game end mode" set to `neverend`
- Place commander and press start
- Run the command `/runtests`

### CODE REVIEW

**Comment by saurtron** [comment]
Tested this by adding a couple extra test_xxx functions at a test file and seems to work fine.

Thank you for this it's a great addition.

**Comment by keelefi** [comment]
Close as we plan to take a different approach. See: https://discord.com/channels/549281623154229250/1194505222605778984/1314762440319307857

**Comment by saurtron** [comment]
You sure? I didn't get the impression that would affect this, just different/expanded vocabulary for tests.

**Comment by keelefi** [comment]
> You sure? I didn't get the impression that would affect this, just different/expanded vocabulary for tests.

With this PR the idea was that you declare tests like `function testCreateFerryRoutes()` while the new plan laid out would be to use a style such as what [busted](https://github.com/lunarmodules/busted) is using.  Then, tests are declared like `it("test create ferry routes", <blaa blaa>)`.

The code changes in this PR are mainly involving the functionality to discover `test*()` functions which we no longer desire to have.

**Comment by saurtron** [comment]
Ok, if using the `describe` method at the testfile toplevel then that would be the natural way to specify tests for the suite, I guess, in that case you are probably right to close this, but also probably most of the work can be reused just change the discovery a bit to use `describe`.

Lets hope that's easily feasible though and doesn't generate problems, because lua scope rules are a bit finicky when playing together with the SyncedRun and SyncedProxy mechanisms.

**Pull request closed without merging**
