### PR TITLE
Additional Debug command Terraforming Options

### PR DESCRIPTION
**Pull request by robertthepie**
Adds 3 to 7 new terraforming options, depending on how you count them, into the debug command prompt, on top of the pre-existing invertmap.
These commands can be queued, seperating them by comma, basically allowing create new map expirances out of preexisting maps.
The commands added are:
- **minheight/maxheight [height]** - flips valleys/hills bellow/above specified height into hills/valleys
- **extreme [mult] / extremeabove/extremebelow [height] [mult]** - multiplies the height extremety of all/above-height/bellow-height making slopes steeper/smoother
- **flatten/floor [height]** - turns anything above/bellow flat to the specified height
also adds duplicate waterlevel to ease sharing of lists

the parameter request for height can be replaced with `mode [int]`, which will be replaced with a height value from a list of heights sorted by the most common height, grouped in steps of 16, to ease the sampling of points to use for the user.
If the keyword mode is involved in terraforming a table listing these heights will be added to the game logged.

### CODE REVIEW

**Comment by TheSilverHornet** [comment]
I've tested this at some extent, it's definitely worth adding

**Comment by Beherith** [comment]
I'm generally not a fan of the entire Invertmap one, as it screws up pre-calculated normals and ambient occlusion. But otherwise, I like the ideas presented here.

**Comment by 6AKU66** [comment]
Can someone a problem with normals and ambient occlusion can be solved?

**Comment by TheSilverHornet** [comment]
Invertmap isn't new functionality, so shouldn't block merging of this.  However it would be nice to address that issue later, if it's possible to at runtime.

**Comment by Damgam** [comment]
yolo

**Pull request merged**
