### PR TITLE
Increase Energy Conversion Cap From 1 to 2

### PR DESCRIPTION
**Pull request by RealArgonwolf**
This will (hopefully) allow the maximum value of the "multiplier_energyconversion" modoption (displayed as "Energy Conversion Efficiency Multiplier" in the UI) to be set as high as 10. The UI already allows numbers up to 10 to be entered, but the setting will fail in a multiplayer game if set in excess of 1.

This time I'd like to ask somebody more familiar with the game if this will actually allow the intended change, as it wasn't clear when making my previous request to update the chobby that it would fail in multiplayer lobbies (it works fine in single player).

### CODE REVIEW

**Comment by Ruwetuin** [comment]
I am of the opinion that players shouldnt make energy convertors (wildly) more viable then metal extractors

**Comment by Ruwetuin** [comment]
I must also note that previously it was about energy convertor capacity which is a different thing from efficiency

**Comment by 6AKU66** [comment]
> I am of the opinion that players shouldnt make energy convertors (wildly) more viable then metal extractors

It's for non-metal maps and settings as i understand.
Also all (or almost all) settings can be set to x10.

**Comment by RealArgonwolf** [comment]
> I am of the opinion that players shouldnt make energy convertors (wildly) more viable then metal extractors

That's fine, but nobody's forced to play with increased converter efficiency any more than any other mod. I just think it would be nice to have the option for those who do like such tweaks.

**Comment by RealArgonwolf** [comment]
I myself don't host games with increased conversion rates; I actually made this request because I play a lot of BrightWorks's stream lobbies and he regularly uses a workaround to set 2x conversion efficiency (by doubling overall resource production and then halving energy generation and metal extraction). It's also possible via unit tweaks but it would be more convenient to be able to simply set the value directly in the UI.

**Comment by Ruwetuin** [comment]
if the cap would be 2 instead of 10 then i wouldnt have much of an objection

**Comment by RealArgonwolf** [comment]
> if the cap would be 2 instead of 10 then i wouldnt have much of an objection

Deal. I'll also go make a pull request in the chobby to revert the max 10 allowed in the UI down to 2 since it already got updated to 10.

**Pull request merged**
