### PR TITLE
part 3 of hitbox changes

### PR DESCRIPTION
**Pull request by drivver44**
in this there are .s3o file changes as the wrecks do not have a properly centered radii. i simply clicked estimate on both model center and radii size.
for maverick/commander wrecks
moved the hit box to not be floating in the air

i do have concerns regarding com wrecks placement change but it should be fine

### CODE REVIEW

**Comment by drivver44** [comment]
dont merge yet forgot commander unit defs

**Comment by drivver44** [comment]
for commander wrecks this fixes the current set of issues
1. makes the wreck hitbox the same for both commanders (arm was smaller)
2. makes the heap box the same for both commanders
3. makes the heap hitbox the same as the wreck hitbox (it was possible to dgun a wreck and turn the commanderr wreck into a heap)

**Comment by drivver44** [comment]
do not merge a mistake for corcom_dead is currently in

**Comment by drivver44** [comment]
added fix for cortoaster 


need to add this

there is something wrong with dgun aimpoint 
this PR resolves the issue of DGUN not fully destroying commander reclaim at long ranges
but at short ranges its still possible to leave relcaim behind

**Review by Zecrus2 — APPROVED** [review]

**Pull request merged**
