### PR TITLE
Raptor eco pathing update

### PR DESCRIPTION
**Pull request by ScottMcNaught**
The reason for this PR:

If you play any multiplayer raptors game (with a high number of players), you'll see talk of T2 eco in the chat.  "Don't do it!" etc.

Often, a new player will innocently early-build a T2 wind, or T2 converter.  When that happens, the entire maps worth of raptors targets them. That player will be annihilated, and left confused.  The players next to that one will be wiped out by the wave as well, leaving them salty.

The previous implementation had a naïve list of 'high value targets'.  When one existed, it drew the whole maps raptors attention.

This PR instead creates weighted sets of targets based on the eco produced by that building type.  It is performant as it uses sets based on the eco value of the unit.  

There are commented out lines of Spring.Echo() calls which show how it works.

Similar pathing code is present in scavs, so it should be ported there too.

### CODE REVIEW

**Comment by ScottMcNaught** [comment]
How it works:
On "UnitCreated", build sets of targets indexed on eco weight:

`Eg:
{
     1: [non-eco]
    25: [t1 windmill, t1 solar, t1 mex],
    75: [adv solar]
    1000: [fusion]
    3000: [adv fusion]
}`


getRandomEnemyPos() then uses the sets as follows:
Calculate the 'max eco' by summing each weight * unit count for each set
Generate a random number constrained to 'max eco', and find a weighted set that it fits in
Pick a random unit from that set

**Comment by ScottMcNaught** [comment]
distribution

**Comment by ScottMcNaught** [comment]
weighted
Distribution path screenshot

**Comment by peanutsrevenge** [comment]
I'm not certain, but I think tidal needs explicit ... something, as with turbines.
I'm seeing far fewer positions around tidal than anything else and what is there could [probably] be spillover from nearby adv solar.

**Pull request merged**
