### PR TITLE
Disable drone carriers when Disable All Air mod option is enabled

### PR DESCRIPTION
**Pull request by nevniv**
### Work done
Disabled any units with drones when air units are also disabled.  I frequently see people make drone carriers or hives when air is disabled because they forget or don't realize that they won't spawn any drones.

The only potential downside I see is that some units have multiple weapons, ex. Cortex Sentinel has both a depth charge launcher and drones and this would also disable that unit.  Open to suggestions but my pea brain may not be able to implement them.

#### Test steps
I checked with disable air mod option disabled and enabled and saw that units like the sentinel, drone carriers, hive were present and then not present.

### CODE REVIEW

**Comment by robertthepie** [comment]
This implementation is kinda questionable.

The parameter `childreninheritxp` is for if the unit inherits the XP of its drones, actual drone spawning is defined in custom params of weapon defs, tho i guess suffices for now, as getting out of there if a unit is an air unit might be akward.
In addition `childreninheritxp` seems to be a space seperated list, so a unit may have more than just drones, tho checking if it is only Drones like it is right now might be preferable.

One thing that i will say for certain is excluding the unit fully simply because it inherits from drones may be bad. Legion Evo comms spawn drones and land bots, if for example a variation was added that only has the air drones it would cause the entire unit to be removed when this is on.
I'd suggest checking the number of weapondefs the unit has? To see if it is capable of more than commanding drones. This would inturn let the T2 legion geo w/ anti nuke also pass i believe.

**Comment by nevniv** [comment]
Argh, I meant to test the legion ageo and forgot.

I was a little worried about the implementation but I was not sure how to iterate through weapondefs on units to look for drones and see if they were the only weapons something had.

I will see if I can figure it out but I am awful with lua and understanding all this dot notation.

To do:
Find alternate exclusion method for drone carriers (try weapondefs?)

retest drone carriers
test legion ageo
test evo com drones

**Comment by robertthepie** [comment]
the dot `.` means you are acessing a parameter inside another, so `uDef.weapondef` is the same as `uDef["weapondef"]`, except the latter is automatically the param name, where as the latter instead of a string can take in a param of most types.

As far as i'm willing to look, dedicated drone carriers only have 1 weapon, so
```lua
elseif #uDef.weapondefs == 1 and uDef.weapondefs[1].customparams and uDef.weapondefs[1].customparams.carried_unit then
	local childDrone = UnitDefs[uDef.weapondefs[1].customparams.carried_unit]
	if childDrone and childDrone.uDef.canfly then
		uDef.maxthisunit = 0
	end
end```
*the hash followed by paramname returns the number of parameters, tho only for sequentially numbered ones starting at 1

**Comment by nevniv** [comment]
I tried to use your code but I got **attempt to get length of field 'weapondefs' (a nil value)**

I tried something more like this because every carried_unit is plasma, I thought it would be more specific and avoid the nil values but it didn't
```lua
elseif uDef.weapondefs.plasma.customparams.carried_unit then
   if #uDef.weapondefs == 1 and uDef.weapondefs[1].customparams and uDef.weapondefs[1].customparams.carried_unit then
   etc...
```
 **attempt to index field 'weapondefs' (a nil value)**

I did still ask about it in the Discord in case I can understand a better way to reference a property inside of a member of an object, or whatever you would call that.  

Anyway, with my last commit, I didn't see any issues in testing, though since it's just plain disabling of units by name I would not think anything too strange would happen.  The buildings grayed out, and the units were just missing from the grid menu (which is the same way it seems to work with AA buildings and units already)

**Comment by robertthepie** [comment]
> I tried to use your code but I got attempt to get length of field 'weapondefs' (a nil value)

Ahh, sorry, i forgot to nil check it, that would just be a simple `uDef,weapondefs and` at the start of the if statement.
If you check a variable, but don't compare it in lua it will pass as true for as long as it is not `nil` (aka it is present) and is not `false`.

```lua
elseif	uDef,weapondefs and
	#uDef.weapondefs == 1 and
	uDef.weapondefs[1].customparams and
	uDef.weapondefs[1].customparams.carried_unit then
	local childDrone = UnitDefs[uDef.weapondefs[1].customparams.carried_unit]
	if childDrone and childDrone.uDef.canfly then
		uDef.maxthisunit = 0
	end
end
```

you need to be sure that the parameter (key) exists inside the object (table) each time you wish to access inside of it via the dot `.` or square brackets `[ ]`

**Comment by sprunk** [comment]
probably more like this
```diff
- local childDrone = UnitDefs[uDef.weapondefs[1].customparams.carried_unit]
- if childDrone and childDrone.uDef.canfly then
+ local childDrone = UnitDefNames[uDef.weapondefs[1].customparams.carried_unit]
+ if childDrone and childDrone.canfly then
```

**Comment by robertthepie** [comment]
Isn't all_defs_post before it gets given to the engine and therefore UnitDefs would still be keyed via names rather than IDs?

**Comment by sprunk** [comment]
right, if it's in posts then it's UnitDefs

**Comment by WatchTheFort** [comment]
Please don't use hardcoded indexes for checking, it means any unit that has a matching weapon, but that doesn't happen to be the first one, fails the check. Use a loop and check every weapon.

```lua
for weaponName, weaponDef in pairs(uDef.weaponDefs) do
  if weaponDef.customparams.carried_unit then
    ...
  end
end
```

**Comment by sprunk** [comment]
Perhaps it's best to just mark units that need to be disabled explicitly? Drone carriers can have other roles and it's up to judgement whether spawning drones is their main role or not

**Comment by robertthepie** [comment]
The snipped of code i wrote with the intention of capturing dedicated drone carriers only, as anything that does more than just drones would have more weapons, but again, that may be subject to change, as we might one day get a builder with a drone or something as an example.

Using the a loop is also not future proofing it, as it would catch units that have a drone on the side, like the legion evocom commanders.

Using a hardcoded list might be the best solution.
Tho your current list i believe doesn't contain the dedicated carriers added via the `extra units` option.

**Comment by sprunk** [comment]
> Well if that's the case, that's what I did with my last commit already. 

no, customparam instead of a table

**Comment by sprunk** [comment]
Don't worry about it. What I suggest (but which @WatchTheFort should first say OK to) is to take each relevant unit, look at its customparams table:
https://github.com/beyond-all-reason/Beyond-All-Reason/blob/faaad06f24e29885c83d4f0446c52cd10204469a/units/Legion/Defenses/leghive.lua#L34-L35

Add a new, explicit "disable when no air" entry to each one like this:
```diff
 customparams = {
+	disable_when_no_air = 1, -- becomes useless since only used to spawn air drones
 	usebuildinggrounddecal = true,
```

And then during preprocessing instead of your hardcoded table, have
```diff
-local DroneCarriers = {
-	armdronecarry = true,
-	...
-}
-if DroneCarriers[name] then
+if uDef.customparams.disable_when_no_air then
	uDef.maxthisunit = 0
```

**Comment by WatchTheFort** [comment]
Isn't this what the category tag is for?

Ideally we could identify air units by their characteristics, rather than with custom labels, but drone carriers are air units that don't fly.

**Comment by nevniv** [comment]
> Isn't this what the category tag is for?
> 
> Ideally we could identify air units by their characteristics, rather than with custom labels, but drone carriers are air units that don't fly.

Just in case you haven't seen it, the code prior to this PR is a smattering of things

customparams.subfolder Aircraft is disabled
Then, anything with unitgroup "aa" is disabled
Then, anything with canfly == true is disabled
Finally, a table of air factories are disabled

If adding more tags is OK, we could add a dronecarrier tag somewhere, but that still doesn't solve the issue that something like a Rampart (Legion Ageo) would be considered a dronecarrier but still we should not disable it just because air is disabled as it has other functionality.  So we still end up either manually excluding a couple of units/buildings on top of the tag (which maybe is OK as it creates less work down the road?)

The alternative is trying something like robertthepie's suggestion of checking if every weapondef on a unit is a carried_unit that canfly, and if so disable it.  Otherwise, leave it enabled.

**Comment by robertthepie** [comment]
> Don't mind me.. apparently can't have two forks, was trying to fix another issue and committed to this one.

You make new branches in your fork and make pull request from those.
You wouldn't really be making pull requests from your fork's master branch but instead from a branch in your fork that is based on upstream master.

**Comment by nevniv** [comment]
Thanks - OK I don't think I have access to change this PR to be based off my new branch, but it does not matter until a decision is made on how this should be implemented anyway.

https://github.com/nevniv/Beyond-All-Reason/tree/Disable-drone-carriers-when-Disable-All-Air-mod-option-is-enabled-%233866-

**Comment by WatchTheFort** [comment]
I think a combination of both is best, disable aircraft by identifying them by their characteristics, and Sprung's suggestion to add a custom param for non-air units that are actually air units.

**Comment by nevniv** [comment]
OK - I think I've done that now in the branch I referenced in my last comment.

I don't think I can change this PR to that branch though.  Is that something one of you can do or should I just close this PR and open a new one?

**Comment by robertthepie** [comment]
Doesn't diable the dedicated land carrier `Nexus Terra` `armdronecarryland` extra unit pack unit.

**Comment by nevniv** [comment]
Are you talking about the scavenger unit?  No, I did not mess with those, although I think that may be the only Scavenger unit that spawns drones

**Comment by robertthepie** [comment]
> I guess the question is, is Scavengers with air disabled something that should be supported? Should I put the customparam on that scavenger vehicle (armdronecarryland)?

sorry it took me so long to respond, didn't see the edit.
Yes, we should work to make modoptions cross compatible.

**Comment by nevniv** [comment]
> > I guess the question is, is Scavengers with air disabled something that should be supported? Should I put the customparam on that scavenger vehicle (armdronecarryland)?
> 
> sorry it took me so long to respond, didn't see the edit. Yes, we should work to make modoptions cross compatible.

OK, easy enough- it's done.

I still can't update this PR to point at the right branch https://github.com/nevniv/Beyond-All-Reason/tree/Disable-drone-carriers-when-Disable-All-Air-mod-option-is-enabled-%233866- but otherwise I think it's done.

**Pull request closed without merging**
