### PR TITLE
The Big Legion Makeover: Alaris Remodel

### PR DESCRIPTION
**Pull request by ZephyrSkies7**
Still waiting on wreck atlas for now, otherwise ready to go.

### Work done
Remodeled Alaris (`leghades`) using Flaka's new texture atlas.

### Screenshots:
image
image
image
image

### CODE REVIEW

**Comment by ChrisFloofyKitsune** [comment]
This can definitely be closed due to being outdated, a different Alaris remodel is in the game now.

**Comment by ZephyrSkies7** [comment]
Close due to being superseded by a better model.

**Comment by sprunk** [comment]
Is this one going to be thrown away then?

**Comment by ZephyrSkies7** [comment]
> Is this one going to be thrown away then?

More than likely, could come back if we find space for a light tank unit thing but tbh this was my 2nd ever model and first I made with the new atlas and it's quite amateurish compared to my newer stuff (which is still amateurish tbh but hey progress is progress). Maybe could be added to Scavs as a "Archaic Alaris" like we have the old Dragon but unlikely, would need to ask @Damgam.

**Comment by sprunk** [comment]
I was about suggest that ZK accepts rejected models but I just realized that I wouldn't actually be able to use the texture atlas.

**Comment by ZephyrSkies7** [comment]
> I was about suggest that ZK accepts rejected models but I just realized that I wouldn't actually be able to use the texture atlas.

If you want I can turn this into a ZK model if I receive the right texture atlas. I'm assuming the process for getting a model into ZK is quite similar to BAR with s3os and such?

**Comment by sprunk** [comment]
ZK has no atlases, modellers must make a texture from scratch. Not worth it probably

**Pull request closed without merging**
