### PR TITLE
Grid UI design improvements

### PR DESCRIPTION
**Pull request by thehobojoe**
### Changes

- Category buttons are now on the bottom, since the category keys are the bottom row of grid keys by default (ZXCV) this makes more intuitive sense.
- Category buttons now have icons that match their purpose
- Hotkey indicators no longer have brackets
- Paging buttons are simplified to a single button that rotates through all the pages
- Paging buttons are now on the top in the default left-side menu, and under the category buttons on the bottom-oriented menu
- Hotkey indicators are now on the top-right of buildpics
- Since hotkeys are on the top-right, category icons are now added to the top-left
- Factory queue placement is now in the top-left and draws over the category icon
- (experimental) Empty spaces in the grid now have a semi-opaque empty buildpic

I think that's everything :)

### Screenshots
spring_kWtSwZupOg
spring_2Syi2tKQI0
spring_2uppPRXns7
spring_UomwFu0lEe

### CODE REVIEW

**Comment by thehobojoe** [comment]
@badosu as usual I would love your code review.

For anyone who wants to test, similar steps as before:

#### Tests
- [ ] Grid menu on the side
- [ ] Grid menu on the bottom
- [ ] Order menu on the side
- [ ] Order menu on the bottom
- [ ] UI scale
- [ ] Various constructors and labs
- [ ] Hotkey behavior with all of the above (should be fine but it never hurts to check)
- [ ] Paging through menus of various sizes

**Comment by resopmok** [comment]
Tested changes, worked as expected. The new design is easier on the eyes and makes the paging key more obvious, especially in the T2 labs that use it. It's also nice that paging cycles and only reserves 1 hotkey.

**Comment by resopmok** [comment]
Tested in-game, skirmish and multiplayer and works as expected. Updated design looks better and new paging is nice to have cycled instead of back and forward, saving us a hotkey. Glad to see some aesthetic love for grid menu!

**Comment by badosu** [comment]
Thank you Hobo for your continued work <3

**Pull request merged**
