### PR TITLE
I18N: Support for empty strings

### PR DESCRIPTION
**Pull request by WatchTheFort**
It turns our removing the validation against empty strings doesn't break anything. Who knew.

### CODE REVIEW

**Comment by sprunk** [comment]
It "breaks" the ability to default empty strings to something meaningful (eg. "<missing translation>" or the source English text).

**Comment by WatchTheFort** [comment]
I tested, this does not break the behaviour of displaying the key name for missing keys, and empty strings are being "displayed" properly. So far it appears that this change has no side effects.

image

**Comment by sprunk** [comment]
> empty strings are being "displayed" properly

That sounds like a bad feature.

**Comment by WatchTheFort** [comment]
What do you mean? If a caption is an empty string, you don't see anything on the UI, the same as when it was a single space.

**Comment by sprunk** [comment]
If a caption is an empty string (or a single space or something similarly stupid) in English then don't put it in i18n.

If it was some actual text in English and it got "translated" into an empty string then it should be treated the same as if it was missing.

**Comment by WatchTheFort** [comment]
The dummy entries with empty strings are for dynamically generated I18N lookups for unit names and descriptions. Not all units have descriptions, so the dummy entry is needed to not have I18N log an error for a missing key.

**Pull request merged**
