### PR TITLE
Armflash script heading check

### PR DESCRIPTION
**Pull request by KyleAnthonyShepherd**
Script now skips wait-for-turn if the heading is good enough. 
armflash is no longer blocked from firing for 3 frames every time AimPrimary is called.
Unit now fires a shot every 0.1 seconds, 3 frames, as specified in the unitdef (a burst of 3 every 0.3 seconds).
However, this means 4 shots are now fired every 12 frames, instead of 3 shots every 12 frames. 
This animation fix will result in a 33% DPS buff for the armflash.
image

### CODE REVIEW

**Comment by KyleAnthonyShepherd** [comment]
ezgif com-gif-maker (16)
Gif instead of screenshot of gif

**Comment by Beherith** [comment]
@Zecrus2  please have a look at this :)

**Comment by Zecrus2** [comment]
This is a good fix, the unit should behave how players expect it to instead of secretly dealing 25% less dps.  I tested it in my local version and didn't see any problems.  This will have a large effect on balance and armflash might end up too powerful, so some changes will be needed to mitigate this.  The damage/shot could be changed to match up with armpw (10/shot) which would match up best with player expectations, or it could be matched up with armdecade (9/shot) which would keep balance close to current (90dps vs 82.5, but with lower alpha).

**Comment by WatchTheFort** [comment]
Or decrease the firing rate to match the previous de facto firing rate.

**Comment by Beherith** [comment]
Ok, so @Zecrus2 can you merge this when you are ready to address the resulting effects? :)

**Comment by Beherith** [comment]
@Zecrus2 ping :)

**Pull request merged**
