### PR TITLE
added widget: "Highlight Commander Wrecks"

### PR DESCRIPTION
**Pull request by Ruwetuin**
default disabled
This widget adds a vertical teamcolorized beam where commander wreckages are

### CODE REVIEW

**Comment by WatchTheFort** [comment]
Why make it an option? Options are already bloated, and this seems useful.

**Comment by Ruwetuin** [comment]
It literally sticks out, so its better to have it as an option, well until there's more feedback that everybody really wants this. It's not something super pretty

**Comment by WatchTheFort** [comment]
Add a teamcolour glow to the wreck itself?

**Comment by Ruwetuin** [comment]
halve the beam height and made it default enabled

**Pull request merged**
