### PR TITLE
Batch 3 of sounds for Legion bots

### PR DESCRIPTION
**Pull request by Arbsquid**
Mostly bot sounds but with the T1 napalm veh in there as well.

### CODE REVIEW

**Comment by icexuick** [comment]
**leg-bar-medium-sel** and **-ok** do not exist.
**legsrail** ok sound I find a bit too long - can you shorten it?
**legbar** movement-sound still a bit long imho - can you start the fade out earlier?

All other sounds are AWESOME!
Really nailed it on legck, but also love Goblin and Proteus

**Comment by WatchTheFort** [comment]
@icexuick Please merge this PR when you deem it ready

**Comment by icexuick** [comment]
@Ruwetuin can we merge this regarding the desync freeze?
I'm okay with merge.

**Review by icexuick — APPROVED** [review]
All good!

**Pull request merged**
