### PR TITLE
[very rough draft] feat(dbg_function_profiler): add widget function profiler

### PR DESCRIPTION
**Pull request by salinecitrine**
Does something pretty similar to widget profiler, but more detailed, and focused on only the widgets that are explicitly profiled.

Using this at the same time as widget profiler will cause issues. Also make sure to unprofile or disable this widget before disabling a widget it's profiling.

---

Usage:

`/profilewidget <widgetname>`
instruments all functions in a widget

`/unprofilewidget <widgetname>`
uninstruments all functions in a widget

`/profilereset`
resets all stats and timers. it's recommended to use this whenever you change what kind of activity you're looking at, since without this, averages are over the whole time the function profiler has been enabled.

Screenshot 2024-05-11 082546

*I'm mostly putting this in a PR so it's easier to share and discuss; I'm not in a rush to merge it, though that is something I am interested in eventually.*

### CODE REVIEW

**Comment by p2004a** [comment]
You are aware of profiling widgets with Tracy, correct?

**Comment by salinecitrine** [comment]
> You are aware of profiling widgets with Tracy, correct?

I don't have much experience with that; when I tried out Tracy I had some trouble getting it capturing things properly.

Does profiling widgets always require switching to a custom engine?

**Comment by p2004a** [comment]
> I had some trouble getting it capturing things properly

You will need to be more specific, because maybe it was just user error ;). I believe Beherith used Tracy quite a bunch for Lua and I've not heard he had any issues.

> Does profiling widgets always require switching to a custom engine?

Yes, using Tracy requires picking engine build with tracing enabled from https://engine-builds.beyondallreason.dev/, just because it might have some overhead (currently there isn't any I was able to measure) it's not on in production build. If that's a major inconvenience to BAR game dev, we consider making it more convenient by adding it as option to the launcher.

The game loading code is also entirely striping calls to Tracy instrumentation from Lua, so there is 0 impact on end players even with some tracing in place in Lua permanently.

And then Tracy also allows for different level of tracing, e.g. tracing memory allocations across engine is pretty heavy, so it's not enabled in the default profiling builds.

**Comment by salinecitrine** [comment]
Thanks for the explanation! I'll give it another try.

> You will need to be more specific, because maybe it was just user error ;). I believe Beherith used Tracy quite a bunch for Lua and I've not heard he had any issues.

I'm pretty confident it was user error :)

**Pull request closed without merging**
