### PR TITLE
Move Attack Range GL4 to use unit tracker api.

### PR DESCRIPTION
**Pull request by Beherith**
#### Test steps
- [ ] Write the steps needed to test out the changes. Include the expected result.

### CODE REVIEW

**Comment by Ruwetuin** [comment]
i see it makes use of myTeamID, but spectators can change teams still, i see no playerchanged event being used

**Comment by Beherith** [comment]
You are correct floris, this widget is quite badly written on that front.

**Comment by Beherith** [comment]
This needs better maxAngleDiff + mainDir to plane calculations. Assistance requested from better math experts.

**Comment by icexuick** [comment]
@Ruwetuin can we pick up on this? I'd love to improve and unify attack ranges + anti ranges + defense ranges.

**Comment by WatchTheFort** [comment]
@Beherith After conflicts are fixed, is this ready for merge?

**Comment by icexuick** [comment]
> @Beherith After conflicts are fixed, is this ready for merge?

Ideally I'd like to use this to use unit-tracker + also stencil the defense + anti-nuke ranges + have some options in settings to set how visible you want the inner rings to be shown.

**Pull request merged**
