### PR TITLE
Unify dgun range

### PR DESCRIPTION
**Pull request by TheSilverHornet**
### Work done
For far too long, the Armada Heathens have had an immeasurable advantage (*measured as 12 elmos) over the Cortex nation, in the form of their extended dgun range !

After untold amounts of effort and research, I present the culmination of the Great Work, a grand nerf striking at the heart of the problem. No longer will we be the butt of their jokes!

#### BEFORE:
image

#### AFTER:
image

### CODE REVIEW

**Comment by Beherith** [comment]
This is two completely different things, the dropship stuff and dgun changes. Please break them into separate PRs.

**Review by StanczakDominik — APPROVED** [review]

**Comment by StanczakDominik** [comment]
actually see #dev-main for discussion on which direction (armcom nerf or corcom buff) is better here

**Comment by sprunk** [comment]
rebase to throw out the two commits that cancel each other?

**Comment by TheSilverHornet** [comment]
> This is two completely different things, the dropship stuff and dgun changes. Please break them into separate PRs.

was actively trying to at the time, no idea how the dropship (not even finished) got caught up. it's removed now.

**Comment by TheSilverHornet** [comment]
> rebase to throw out the two commits that cancel each other?

kind of can't sanely apparently. it's a squashmerge job.

**Comment by StanczakDominik** [comment]
Nothing to worry about if

# PLEASE ONLY SQUASH MERGE THIS

isn't forgotten :D

**Comment by Ruwetuin** [comment]
so this PR got a bit messy.... do i understand it now only buffs cortex dgun range +12 to make its effective range equal to the armada one?

**Pull request merged**
